#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/pub/gnu/cpio/cpio-2.12.tar.bz2"
MD5SUMLIST="93eea9f07c0058c097891c73e4955456"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --bindir=/bin \
            --enable-mt   \
            --with-rmt=/usr/libexec/rmt
make
makeinfo --html            -o doc/html      doc/cpio.texi
makeinfo --html --no-split -o doc/cpio.html doc/cpio.texi
makeinfo --plaintext       -o doc/cpio.txt  doc/cpio.texi

# (*) Don't build documentation
#make -C doc pdf
#make -C doc ps

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/cpio-2.12/html
install -v -m644    doc/html/* \
                    ${FAKEROOT}/usr/share/doc/cpio-2.12/html
install -v -m644    doc/cpio.{html,txt} \
                    ${FAKEROOT}/usr/share/doc/cpio-2.12

# (*) Don't build documentation
#install -v -m644 doc/cpio.{pdf,ps,dvi} \
#                 ${FAKEROOT}/usr/share/doc/cpio-2.12

#################
} # END OF FILE #
#################

