#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://roy.marples.name/downloads/dhcpcd/dhcpcd-6.11.5.tar.xz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="2465624b62c1154f0e89dc69c42c849b
            b4f1623b69c67f10e67ca610ceee56b4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --libexecdir=/lib/dhcpcd \
            --dbdir=/var/lib/dhcpcd
make

make DESTDIR=${FAKEROOT} install

includeBootscript service-dhcpcd

# (*) Example configuration
#cat > /etc/sysconfig/ifconfig.eth0 << "EOF"
#ONBOOT="yes"
#IFACE="eth0"
#SERVICE="dhcpcd"
#DHCP_START="-b -q <insert appropriate start options here>"
#DHCP_STOP="-k <insert additional stop options here>"
#EOF

# (*) Example configuration
#cat > /etc/sysconfig/ifconfig.eth0 << "EOF"
#ONBOOT="yes"
#IFACE="eth0"
#SERVICE="dhcpcd"
#DHCP_START="-b -q -S ip_address=192.168.0.10/24 -S routers=192.168.0.1"
#DHCP_STOP="-k"
#EOF

cat > ${FAKEROOT}/etc/resolv.conf.head << "EOF"
# OpenDNS servers
nameserver 208.67.222.222
nameserver 208.67.220.220
EOF

#################
} # END OF FILE #
#################

