#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

REQUIRES="chromium compiz-reloaded firefox flashplayer fsos-nox gparted gucharmap lxdm mate network-manager-applet qemu transmission vlc"
TAGS="group"

