#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxdm/lxdm-0.5.3.tar.xz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="061caae432634e6db38bbdc84bc6ffa0
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="gtk+2 iso-codes librsvg linux-pam xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cat > pam/lxdm << "EOF"
# Begin /etc/pam.d/lxdm

auth     requisite      pam_nologin.so
auth     required       pam_env.so
auth     include        system-auth

account  include        system-account

password include        system-password

session  required       pam_limits.so
session  include        system-session

# End /etc/pam.d/lxdm
EOF

sed -i 's:sysconfig/i18n:profile.d/i18n.sh:g' data/lxdm.in
sed -i 's:/etc/xprofile:/etc/profile:g' data/Xsession
sed -e 's/^bg/#&/'        \
    -e '/reset=1/ s/# //' \
    -e 's/logou$/logout/' \
    -e "/arg=/a arg=$XORG_PREFIX/bin/X" \
    -i data/lxdm.conf.in

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-pam        \
            --with-systemdsystemunitdir=no
make

make DESTDIR=${FAKEROOT} install

includeBootscript lxdm

# (*) Example configuration
#/etc/rc.d/init.d/lxdm start

# (*) Example configuration
#init 5

# (*) Example configuration
#cp -v /etc/inittab{,-orig}
#sed -i '/initdefault/ s/3/5/' /etc/inittab

#################
} # END OF FILE #
#################

