#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="https://www.kernel.org/pub/linux/utils/boot/syslinux/Testing/6.04/syslinux-6.04-pre1.tar.xz"
MD5SUMLIST="f9c956fde0de29be297402ecbc8ff4d0"
REQUIRES="nasm python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed 's@win32/syslinux.exe win64/syslinux64.exe \\@\\@g' -i Makefile

#make spotless

make -j1 bios

make INSTALLROOT=${FAKEROOT} -j1 bios install

#################
} # END OF FILE #
#################

