#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.3.tar.bz2"
MD5SUMLIST="eefe5992567ba00d6110a540657aaf5c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure
make

# (*) Suppress the building of documentation which requires additional software to be installed
#make doc

make DESTDIR=${FAKEROOT} install

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -d -m755 ${FAKEROOT}/usr/share/doc/alsa-lib-1.1.3/html/search
#install -v -m644 doc/doxygen/html/*.* \
#                ${FAKEROOT}/usr/share/doc/alsa-lib-1.1.3/html
#install -v -m644 doc/doxygen/html/search/* \
#                ${FAKEROOT}/usr/share/doc/alsa-lib-1.1.3/html/search

#################
} # END OF FILE #
#################

