#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.1.3.tar.bz2
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="2bf94d3e3410dcc74bb0dae10d46a979
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="alsa-lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --disable-alsaconf \
            --disable-bat   \
            --disable-xmlto \
            --with-curses=ncursesw
make

make DESTDIR=${FAKEROOT} install

# (*) Example configuration
#alsactl -L store

# (*) Example configuration
#usermod -a -G audio <username>

includeBootscript alsa

#################
} # END OF FILE #
#################

