#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/atk/2.24/atk-2.24.0.tar.xz"
MD5SUMLIST="3747a80089dfa3c0bbcf21adfff9968b"
REQUIRES="glib2"
RECOMMENDS="gobject-introspection"

# (*) Install 'gobject-introspection' because it avoids compilation order problems when building Gnome

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

