#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/autoconf/autoconf-2.13.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/autoconf-2.13-consolidated_fixes-1.patch"
MD5SUMLIST="9de56d4a161a723228220b0f425dc711
            9ceaee69e62767770eb473d5242db70d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../autoconf-2.13-consolidated_fixes-1.patch
mv -v autoconf.texi autoconf213.texi
rm -v autoconf.info
./configure --prefix=/usr --program-suffix=2.13
make

make DESTDIR=${FAKEROOT} install
install -v -m644 autoconf213.info ${FAKEROOT}/usr/share/info
install-info --info-dir=/usr/share/info autoconf213.info

#################
} # END OF FILE #
#################

