#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://c-ares.haxx.se/download/c-ares-1.12.0.tar.gz"
MD5SUMLIST="2ca44be1715cd2c5666a165d35788424"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

