#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://cairographics.org/releases/cairo-1.14.8.tar.xz"
MD5SUMLIST="4ef0db2eacb271c74f8a3fd87822aa98"
REQUIRES="libpng pixman"
RECOMMENDS="xorg"

# (*) Install 'xorg' because it is required to build GTK+2

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --enable-tee
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

