#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://cairographics.org/releases/cairomm-1.12.2.tar.gz"
MD5SUMLIST="9d2282ea34cf9aaa89208bb4bb911909"
REQUIRES="cairo libsigc++"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e '/^libdocdir =/ s/$(book_name)/cairomm-1.12.2/' \
    -i docs/Makefile.in

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

