#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.cmake.org/files/v3.8/cmake-3.8.0.tar.gz"
MD5SUMLIST="f28cba717ba38ad82a488daed8f45b5b"
REQUIRES="curl libarchive"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/CMAKE_USE_LIBUV 1/s/1/0/' CMakeLists.txt
sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake

./bootstrap --prefix=/usr        \
            --system-libs        \
            --mandir=/share/man  \
            --no-system-jsoncpp  \
            --no-system-librhash \
            --docdir=/share/doc/cmake-3.8.0
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

