#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz"
MD5SUMLIST="de11011aff801dc61042828041fb59c7"
REQUIRES="glib2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

# (*) Do not use aspell
#ln -svfn ../../lib/aspell /usr/share/enchant/aspell

# (*) Do not use aspell
#cat > /tmp/test-enchant.txt << "EOF"
#Tel me more abot linux
#Ther ar so many commads
#EOF
#
#enchant -d en_GB -l /tmp/test-enchant.txt
#enchant -d en_GB -a /tmp/test-enchant.txt

#################
} # END OF FILE #
#################

