#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/fluxbox/fluxbox-1.3.7.tar.xz"
MD5SUMLIST="b44afd10ee1e64624c23115aa51dcd55"
REQUIRES="xorg"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

echo startfluxbox > ${FAKEROOT}/etc/alternatives/xinitrc/fluxbox.xinitrc

mkdir -v ${FAKEROOT}/etc/skel/.fluxbox
cp -v ${FAKEROOT}/usr/share/fluxbox/init ${FAKEROOT}/etc/skel/.fluxbox/init
cp -v ${FAKEROOT}/usr/share/fluxbox/keys ${FAKEROOT}/etc/skel/.fluxbox/keys

# (*) Example configuration
#cd ${FAKEROOT}/etc/skel/.fluxbox
#fluxbox-generate_menu <user_options>

cp -v ${FAKEROOT}/usr/share/fluxbox/menu ${FAKEROOT}/etc/skel/.fluxbox/menu

# (*) Example configuration
#cp ${FAKEROOT}/usr/share/fluxbox/styles/<theme> ${FAKEROOT}/etc/skel/.fluxbox/theme
#
#sed -i 's,\(session.styleFile:\).*,\1 ${FAKEROOT}/etc/skel/.fluxbox/theme,' ${FAKEROOT}/etc/skel/.fluxbox/init
#
#[ -f ${FAKEROOT}/etc/skel/.fluxbox/theme ]
#echo "background.pixmap: </path/to/nice/image.ext>" >> ${FAKEROOT}/etc/skel/.fluxbox/theme ||
#[ -d ${FAKEROOT}/etc/skel/.fluxbox/theme ]
#echo "background.pixmap: </path/to/nice/image.ext>" >> ${FAKEROOT}/etc/skel/.fluxbox/theme/theme.cfg

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

mkdir -pv /usr/share/xsessions
cat > /usr/share/xsessions/fluxbox.desktop << "EOF"
[Desktop Entry]
Encoding=UTF-8
Name=Fluxbox
Comment=This session logs you into Fluxbox
Exec=startfluxbox
Type=Application
EOF

#################
} # END OF FILE #
#################

