#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.12.1.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/fontconfig-2.12.1-gperf-3.1-1.patch"
MD5SUMLIST="b5af5a423ee3b5cfc34846838963c058
            fced6f98a9fc8c434e5907b610d220ef"
REQUIRES="freetype2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../fontconfig-2.12.1-gperf-3.1-1.patch

sed -e '/FC_CHAR_WIDTH/s/CHAR_WIDTH/CHARWIDTH/'             \
    -e '/FC_CHARWIDTH/a #define FC_CHAR_WIDTH FC_CHARWIDTH' \
    -i fontconfig/fontconfig.h
sed 's/CHAR_WIDTH/CHARWIDTH/' -i src/fcobjs.h

autoreconf -fi
./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-docs       \
            --docdir=/usr/share/doc/fontconfig-2.12.1
make

make DESTDIR=${FAKEROOT} install

install -v -dm755 \
        ${FAKEROOT}/usr/share/{man/man{3,5},doc/fontconfig-2.12.1/fontconfig-devel}
install -v -m644 fc-*/*.1         ${FAKEROOT}/usr/share/man/man1
install -v -m644 doc/*.3          ${FAKEROOT}/usr/share/man/man3
install -v -m644 doc/fonts-conf.5 ${FAKEROOT}/usr/share/man/man5
install -v -m644 doc/fontconfig-devel/* \
                                  ${FAKEROOT}/usr/share/doc/fontconfig-2.12.1/fontconfig-devel
install -v -m644 doc/*.{pdf,sgml,txt,html} \
                                  ${FAKEROOT}/usr/share/doc/fontconfig-2.12.1

#################
} # END OF FILE #
#################

