#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.6.tar.xz"
MD5SUMLIST="5dd53760750670d27c194ff6ace7eb51"
REQUIRES="glib2 libjpeg-turbo libpng libtiff"
RECOMMENDS="gobject-introspection xorg"
POSTINST="true"

# (*) Install 'gobject-introspection' because it avoids compilation order problems when building Gnome
# (*) Install 'xorg' because many GTK+ applications require gdk-pixbuf-xlib

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-x11
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gdk-pixbuf-query-loaders --update-cache

#################
} # END OF FILE #
#################

