#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/glib/2.52/glib-2.52.1.tar.xz"
MD5SUMLIST="36b4c7bf4f2b398ac8ad90578d05c950"
REQUIRES="libffi pcre python2 python3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-pcre=system
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

