#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.freedesktop.org/pub/mesa/glu/glu-9.0.0.tar.bz2"
MD5SUMLIST="be9249132ff49275461cf92039083030"
REQUIRES="mesa xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=$XORG_PREFIX --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

