#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/3.20/gnome-keyring-3.20.0.tar.xz"
MD5SUMLIST="e09efe8021944dae404736b5a2adb98e"
REQUIRES="dbus docbook-xsl gcr"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -r 's:"(/desktop):"/org/gnome\1:' schema/*.xml

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --with-pam-dir=/lib/security
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

