#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-3.5.11.tar.xz"
MD5SUMLIST="a3ff8cf5ca7522e3ba14f487e6326e11"
REQUIRES="libunistring nettle p11-kit"
RECOMMENDS="libtasn1"

# (*) Install 'libtasn1' because it will otherwise install it's own outdated version

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-default-trust-store-file=/etc/ssl/ca-bundle.crt
make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} -C doc/reference install-data-local

#################
} # END OF FILE #
#################

