#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/gparted/gparted-0.28.1.tar.gz"
MD5SUMLIST="ab72464a3ab2137664d9df8462befd3f"
REQUIRES="gtkmm2 parted"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-doc    \
            --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

