#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/silnrsi/graphite/releases/download/1.3.9/graphite2-1.3.9.tgz"
MD5SUMLIST="17e6a3b1a88c100c9e3fc0763c85d269"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/cmptest/d' tests/CMakeLists.txt

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make

# (*) Don't build documentation
#make docs

make DESTDIR=${FAKEROOT} install

# (*) Don't build documentation
#install -v -d -m755 ${FAKEROOT}/usr/share/doc/graphite2-1.3.9/api
#cp      -v -r -f    doc/doxygen/{html,latex/refman.pdf} \
#                    ${FAKEROOT}/usr/share/doc/graphite2-1.3.9/api
#cp      -v -r -f    doc/{GTF,manual}.html \
#                    ${FAKEROOT}/usr/share/doc/graphite2-1.3.9

#################
} # END OF FILE #
#################

