#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gsettings-desktop-schemas/3.24/gsettings-desktop-schemas-3.24.0.tar.xz"
MD5SUMLIST="cc3465621bea4ff6de915812fadc5a8e"
REQUIRES="glib2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

glib-compile-schemas /usr/share/glib-2.0/schemas

#################
} # END OF FILE #
#################

