#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.31.tar.xz"
MD5SUMLIST="526a1008586094a2cbb4592fd3f9ee10"
REQUIRES="atk gdk-pixbuf pango"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e 's#l \(gtk-.*\).sgml#& -o \1#' \
    -i docs/{faq,tutorial}/Makefile.in

./configure --prefix=/usr --sysconfdir=/etc

make

make DESTDIR=${FAKEROOT} install

# (*) Example configuration
#cat > ${FAKEROOT}/etc/skel/.gtkrc-2.0 << "EOF"
#include "/usr/share/themes/Glider/gtk-2.0/gtkrc"
#gtk-icon-theme-name = "hicolor"
#EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-query-immodules-2.0 --update-cache

# (*) Example configuration
#cat > /etc/gtk-2.0/gtkrc << "EOF"
#include "/usr/share/themes/Clearlooks/gtk-2.0/gtkrc"
#gtk-icon-theme-name = "elementary"
#EOF

# (*) Update icon cache
gtk-update-icon-cache

#################
} # END OF FILE #
#################

