#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gucharmap/9.0/gucharmap-9.0.2.tar.xz"
MD5SUMLIST="2d953eb99509fde539f70b527c23eec8"
REQUIRES="desktop-file-utils gtk+3 itstool unzip vala wget"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-vala \
            --with-unicode-data=download
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

