#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gvfs/1.30/gvfs-1.30.3.tar.xz"
MD5SUMLIST="2490ef552dd786cf6fd49eae4ebadaf0"
REQUIRES="dbus docbook-xsl gcr glib2 polkit"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --disable-gphoto2
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

glib-compile-schemas /usr/share/glib-2.0/schemas

#################
} # END OF FILE #
#################

