#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.4.6.tar.bz2"
MD5SUMLIST="e246c08a3bac98e31e731b2a1bf97edf"
REQUIRES="glib2"
RECOMMENDS="freetype2 icu"

# (*) Install 'freetype2' because it is required to build Pango
# (*) Install 'icu' because it is required to build WebkitGTK

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-gobject
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

