#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.icu-project.org/files/icu4c/59.1/icu4c-59_1-src.tgz"
MD5SUMLIST="54923fa9fab5b2b83f235fb72523de37"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd source
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

