#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://pkg-isocodes.alioth.debian.org/downloads/iso-codes-3.75.tar.xz"
MD5SUMLIST="9ba173b69d4360003414f23837597a92"
REQUIRES="python3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

sed -i '/^LN_S/s/s/sfvn/' */Makefile

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

