#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://people.mozilla.org/~sstangl/mozjs-38.2.1.rc0.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/js38-38.2.1-upstream_fixes-2.patch"
MD5SUMLIST="cb602e21f5fc798b88163a3aa4e03e0a
            84a90e648137fb77afcf8e815a910c97"
REQUIRES="autoconf213 icu libffi nspr python2 zip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../js38-38.2.1-upstream_fixes-2.patch

cd js/src
autoconf2.13

SHELL=/bin/sh                   \
./configure --prefix=/usr       \
            --with-intl-api     \
            --with-system-zlib  \
            --with-system-ffi   \
            --with-system-nspr  \
            --with-system-icu   \
            --enable-threadsafe \
            --enable-readline
make

make DESTDIR=${FAKEROOT} install
pushd ${FAKEROOT}/usr/include/mozjs-38
for link in `find . -type l`; do
    header=`readlink $link`
    rm -f $link
    cp -pv $header $link
    chmod 644 $link
done
popd

#################
} # END OF FILE #
#################

