#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://s3.amazonaws.com/json-c_releases/releases/json-c-0.12.1.tar.gz"
MD5SUMLIST="55f7853f7d8cf664554ce3fa71bf1c7d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i s/-Werror// Makefile.in tests/Makefile.in
./configure --prefix=/usr --disable-static
make -j1

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

