#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.libarchive.org/downloads/libarchive-3.3.1.tar.gz"
MD5SUMLIST="d2af45480aa5b0db5b5f3919cd0ea65e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

