#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://dri.freedesktop.org/libdrm/libdrm-2.4.78.tar.bz2"
MD5SUMLIST="049ee80ce816cbef7669e7807b2ee816"
RECOMMENDS="x7lib"

# (*) Install 'x7lib' because it enables Intel KMS API support required by Mesa (and Mesa requires x7lib anyway)

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-udev
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

