#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.7.6.tar.bz2"
MD5SUMLIST="54e180679a7ae4d090f8689ca32b654c"
REQUIRES="libgpg-error"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

# (*) Suppress the building of documentation which requires additional software to be installed
#make -C doc pdf ps html
#makeinfo --html --no-split -o doc/gcrypt_nochunks.html doc/gcrypt.texi
#makeinfo --plaintext       -o doc/gcrypt.txt           doc/gcrypt.texi

make DESTDIR=${FAKEROOT} install
install -v -dm755   ${FAKEROOT}/usr/share/doc/libgcrypt-1.7.6
install -v -m644    README doc/{README.apichanges,fips*,libgcrypt*} \
                    ${FAKEROOT}/usr/share/doc/libgcrypt-1.7.6

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -dm755   ${FAKEROOT}/usr/share/doc/libgcrypt-1.7.6/html
#install -v -m644 doc/gcrypt.html/* \
#                    ${FAKEROOT}/usr/share/doc/libgcrypt-1.7.6/html
#install -v -m644 doc/gcrypt_nochunks.html \
#                    ${FAKEROOT}/usr/share/doc/libgcrypt-1.7.6
#install -v -m644 doc/gcrypt.{pdf,ps,dvi,txt,texi} \
#                    ${FAKEROOT}/usr/share/doc/libgcrypt-1.7.6

#################
} # END OF FILE #
#################

