#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.freedesktop.org/software/libinput/libinput-1.7.1.tar.xz"
MD5SUMLIST="e3b9160f9befa55813327da39642947b"
REQUIRES="libevdev mtdev xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG       \
            --disable-libwacom \
            --with-udev-dir=/lib/udev
make

# (*) Only required for test suite
#ln -sfv ld-2.23.so.dbg /lib/ld-linux-x86-64.so.2

# (*) Don't run test suites.
#make check

make DESTDIR=${FAKEROOT} install

install -v -dm755 ${FAKEROOT}${XORG_PREFIX}/share/doc/libinput-1.7.1
cp -rv doc/html/* ${FAKEROOT}${XORG_PREFIX}/share/doc/libinput-1.7.1

#################
} # END OF FILE #
#################

