#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/libpng/libpng-1.6.29.tar.xz
          http://downloads.sourceforge.net/project/apng/libpng/libpng16/libpng-1.6.29-apng.patch.gz"
MD5SUMLIST="3245dbd76ea91e1437507357b858ec97
            ce2a80d9c6ec19747d971d43ab3c3b40"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

gzip -cd ../libpng-1.6.29-apng.patch.gz | patch -p0

LIBS=-lpthread ./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install
mkdir -v ${FAKEROOT}/usr/share/doc/libpng-1.6.29
cp -v README libpng-manual.txt ${FAKEROOT}/usr/share/doc/libpng-1.6.29

#################
} # END OF FILE #
#################

