#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/libsoup/2.58/libsoup-2.58.0.tar.xz"
MD5SUMLIST="5269bf29bbdd1fed87c02e94d9927bd2"
REQUIRES="glib-networking libxml2 sqlite"
RECOMMENDS="gobject-introspection vala"

# (*) Install 'gobject-introspection' because it is required to build WebkitGTK
# (*) Install 'vala' because it is required when building with gobject-introspection

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

