#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/libtasn1/libtasn1-4.10.tar.gz"
MD5SUMLIST="f4faffdf63969d0e4e6df43b9679e8e5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} -C doc/reference install-data-local

#################
} # END OF FILE #
#################

