#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz"
MD5SUMLIST="28cb28097c07a735d6af56e598e1c90f"
REQUIRES="libogg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/components.png \\/{n;d}' doc/Makefile.in

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install
install -v -m644 doc/Vorbis* ${FAKEROOT}/usr/share/doc/libvorbis-1.3.5

#################
} # END OF FILE #
#################

