#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.6.1.tar.bz2"
MD5SUMLIST="a19518c8111fa93bdabdd85259162611"
REQUIRES="which yasm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/cp -p/cp/' build/make/Makefile

mkdir libvpx-build
cd    libvpx-build

../configure --prefix=/usr    \
             --enable-shared  \
             --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

