#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://people.freedesktop.org/~aplattner/vdpau/libvdpau-1.1.1.tar.bz2"
MD5SUMLIST="2fa0b05a4f4d06791eec83bc9c854d14"
REQUIRES="x7lib xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG \
            --docdir=/usr/share/doc/libvdpau-1.1.1
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

