#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.lua.org/ftp/lua-5.3.4.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/lua-5.3.4-shared_library-1.patch"
MD5SUMLIST="53a9c68bcc0eda58bdc2095ad5cdfc63
            63ecacd3ff6552537a73f8c30c396caf"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cat > lua.pc << "EOF"
V=5.3
R=5.3.4

prefix=/usr
INSTALL_BIN=${prefix}/bin
INSTALL_INC=${prefix}/include
INSTALL_LIB=${prefix}/lib
INSTALL_MAN=${prefix}/share/man/man1
INSTALL_LMOD=${prefix}/share/lua/${V}
INSTALL_CMOD=${prefix}/lib/lua/${V}
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: ${R}
Requires:
Libs: -L${libdir} -llua -lm -ldl
Cflags: -I${includedir}
EOF

patch -Np1 -i ../lua-5.3.4-shared_library-1.patch
sed -i '/#define LUA_ROOT/s:/usr/local/:/usr/:' src/luaconf.h

make MYCFLAGS="-DLUA_COMPAT_5_2 -DLUA_COMPAT_5_1" linux

make INSTALL_TOP=${FAKEROOT}/usr                \
     INSTALL_DATA="cp -d"            \
     INSTALL_MAN=/usr/share/man/man1 \
     TO_LIB="liblua.so liblua.so.5.3 liblua.so.5.3.4" \
     install

mkdir -pv                      ${FAKEROOT}/usr/share/doc/lua-5.3.4
cp -v doc/*.{html,css,gif,png} ${FAKEROOT}/usr/share/doc/lua-5.3.4

install -v -m644 -D lua.pc ${FAKEROOT}/usr/lib/pkgconfig/lua.pc

#################
} # END OF FILE #
#################

