#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz"
MD5SUMLIST="39d3f3f9c55c87b1e5d6888e1420f4b5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                    \
            --enable-shared                  \
            --disable-static                 \
            --docdir=/usr/share/doc/lzo-2.10
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

