#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.nano-editor.org/dist/v2.8/nano-2.8.1.tar.xz"
MD5SUMLIST="57393f25f6cc3fb1de455df743819e29"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-utf8     \
            --docdir=/usr/share/doc/nano-2.8.1
make

make DESTDIR=${FAKEROOT} install
install -v -m644 doc/nano.html ${FAKEROOT}/usr/share/doc/nano-2.8.1

# (*) Configure and use sample configuration
install -v -m644 doc/sample.nanorc ${FAKEROOT}/etc/nanorc

#################
} # END OF FILE #
#################

