#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/nasm-2.12.02.tar.xz
          http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/nasm-2.12.02-xdoc.tar.xz"
MD5SUMLIST="b90a3d85b93e51a7fa5a67e2a8fccfef
            8dfcf5540e782a9c4d4df0bbfbc9c242"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf ../nasm-2.12.02-xdoc.tar.xz --strip-components=1

./configure --prefix=/usr
make

make INSTALLROOT=${FAKEROOT} install

install -m755 -d         ${FAKEROOT}/usr/share/doc/nasm-2.12.02/html
cp -v doc/html/*.html    ${FAKEROOT}/usr/share/doc/nasm-2.12.02/html
cp -v doc/*.{txt,ps,pdf} ${FAKEROOT}/usr/share/doc/nasm-2.12.02
cp -v doc/info/*         ${FAKEROOT}/usr/share/info
install-info ${FAKEROOT}/usr/share/info/nasm.info ${FAKEROOT}/usr/share/info/dir

#################
} # END OF FILE #
#################

