#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://ftp.gnu.org/gnu/nettle/nettle-3.3.tar.gz"
MD5SUMLIST="10f969f78a463704ae73529978148dbe"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install
chmod   -v   755 ${FAKEROOT}/usr/lib/lib{hogweed,nettle}.so
install -v -m755 -d ${FAKEROOT}/usr/share/doc/nettle-3.3
install -v -m644 nettle.html ${FAKEROOT}/usr/share/doc/nettle-3.3

#################
} # END OF FILE #
#################

