#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/network-manager-applet/1.4/network-manager-applet-1.4.6.tar.xz"
MD5SUMLIST="7f5bb421678f844649d8d581def2191e"
REQUIRES="gtk+3 iso-codes libnotify libsecret modemmanager networkmanager"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr       \
            --sysconfdir=/etc   \
            --disable-static    \
            --without-team
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

