#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://nmap.org/dist/nmap-7.40.tar.bz2"
MD5SUMLIST="9c5a28bfb46228bade82b238408c065e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-liblua=included
make

sed -i 's/lib./lib/' zenmap/test/run_tests.py

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

