#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/nodejs/node/archive/v7.9.0.tar.gz"
MD5SUMLIST="cef1dc78e5e4bdeb875fce58baa10a7d"
REQUIRES="c-ares python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr          \
            --shared-cares         \
            --shared-openssl       \
            --shared-zlib          \
            --with-intl=small-icu
make

make DESTDIR=${FAKEROOT} install
ln -sf node ${FAKEROOT}/usr/share/doc/node-7.9.0

#################
} # END OF FILE #
#################

