#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_3_30_2_RTM/src/nss-3.30.2.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/nss-3.30.2-standalone-1.patch"
MD5SUMLIST="42c22dd8ec6254f846259f1d8dd2eb76
            de3565f9e38914f5035fc62c30f3a055"
REQUIRES="nspr"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../nss-3.30.2-standalone-1.patch

cd nss

make -j1 BUILD_OPT=1                  \
  NSPR_INCLUDE_DIR=/usr/include/nspr  \
  USE_SYSTEM_ZLIB=1                   \
  ZLIB_LIBS=-lz                       \
  $([ $(uname -m) = x86_64 ] && echo USE_64=1) \
  $([ -f /usr/include/sqlite3.h ] && echo NSS_USE_SYSTEM_SQLITE=1)

cd ../dist

install -v -m755 Linux*/lib/*.so              ${FAKEROOT}/usr/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} ${FAKEROOT}/usr/lib

install -v -m755 -d                           ${FAKEROOT}/usr/include/nss
cp -v -RL {public,private}/nss/*              ${FAKEROOT}/usr/include/nss
chmod -v 644                                  ${FAKEROOT}/usr/include/nss/*

install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} ${FAKEROOT}/usr/bin

install -v -m644 Linux*/lib/pkgconfig/nss.pc  ${FAKEROOT}/usr/lib/pkgconfig

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

if [ -e /usr/lib/libp11-kit.so ]; then
  readlink /usr/lib/libnssckbi.so ||
  rm -v /usr/lib/libnssckbi.so
  ln -sfv libp11-kit.so /usr/lib/libnssckbi.so
fi

#################
} # END OF FILE #
#################

