#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/pango/1.40/pango-1.40.5.tar.xz"
MD5SUMLIST="11fb1e94c486507a94c4a905d86e70ce"
REQUIRES="cairo fontconfig freetype2 glib2 harfbuzz"
RECOMMENDS="gobject-introspection"

# (*) Install 'gobject-introspection' because it avoids compilation order problems when building Gnome

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

