#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://poppler.freedesktop.org/poppler-0.54.0.tar.xz
          http://poppler.freedesktop.org/poppler-data-0.4.7.tar.gz"
MD5SUMLIST="ed0b36e3f577e669dcc58bd408cacde6
            636a8f2b9f6df9e7ced8ec0946961eaf"
REQUIRES="fontconfig"
RECOMMENDS="cairo"

# (*) Install 'cairo' because it is required to build Atril

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr               \
            --sysconfdir=/etc           \
            --disable-static            \
            --enable-build-type=release \
            --enable-cmyk               \
            --enable-xpdf-headers       \
            --with-testdatadir=$PWD/testfiles
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d        ${FAKEROOT}/usr/share/doc/poppler-0.54.0
install -v -m644 README*   ${FAKEROOT}/usr/share/doc/poppler-0.54.0
cp -vr glib/reference/html ${FAKEROOT}/usr/share/doc/poppler-0.54.0

tar -xf ../poppler-data-0.4.7.tar.gz
cd poppler-data-0.4.7

make DESTDIR=${FAKEROOT} prefix=/usr install

#################
} # END OF FILE #
#################

