#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://rpm5.org/files/popt/popt-1.16.tar.gz"
MD5SUMLIST="3743beefa3dd6247a73f8f7a32c14c33"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -m755 -d ${FAKEROOT}/usr/share/doc/popt-1.16
#install -v -m644 doxygen/html/* ${FAKEROOT}/usr/share/doc/popt-1.16

#################
} # END OF FILE #
#################

