#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://freedesktop.org/software/pulseaudio/releases/pulseaudio-10.0.tar.xz"
MD5SUMLIST="4950d2799bf55ab91f6b7f990b7f0971"
REQUIRES="json-c libsndfile"
RECOMMENDS="alsa-lib"
POSTINST="now"

# (*) Install 'alsa-lib' because it is required to play sound through ALSA

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-bluez4     \
            --disable-bluez5     \
            --disable-rpath
make

make DESTDIR=${FAKEROOT} install

# (*) Don't remove non-existant file
#rm ${FAKEROOT}/etc/dbus-1/system.d/pulseaudio-system.conf

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sed -i '/load-module module-console-kit/s/^/#/' /etc/pulse/default.pa

#################
} # END OF FILE #
#################

