#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.samba.org/ftp/rsync/src/rsync-3.1.2.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="0f758d7e000c0f7f7d3792610fad70cb
            b4f1623b69c67f10e67ca610ceee56b4"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --without-included-zlib
make

make DESTDIR=${FAKEROOT} install

# (*) Suppress the building of documentation which requires additional software to be installed
#install -v -m755 -d          ${FAKEROOT}/usr/share/doc/rsync-3.1.2/api
#install -v -m644 dox/html/*  ${FAKEROOT}/usr/share/doc/rsync-3.1.2/api

cat > ${FAKEROOT}/etc/rsyncd.conf << "EOF"
# This is a basic rsync configuration file
# It exports a single module without user authentication.

motd file = /home/rsync/welcome.msg
use chroot = yes

[localhost]
    path = /home/rsync
    comment = Default rsync module
    read only = yes
    list = yes
    uid = rsyncd
    gid = rsyncd

EOF

includeBootscript rsyncd

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 48 rsyncd
useradd -c "rsyncd Daemon" -d /home/rsync -g rsyncd \
    -s /bin/false -u 48 rsyncd

#################
} # END OF FILE #
#################

