#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.xz"
MD5SUMLIST="894467211c4ae1dbf8a41bb0d58bbc89"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr   \
            --enable-shared \
            --docdir=/usr/share/doc/ruby-2.4.1
make

make capi

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

