#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://static.rust-lang.org/dist/rustc-1.16.0-src.tar.gz"
MD5SUMLIST="c11d94d9e62f71838b20058f0797357a"
REQUIRES="cmake curl llvm3 python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                          \
  --docdir=/usr/share/doc/rustc-1.16.0             \
  --llvm-root=/opt/llvm3 --enable-llvm-link-shared
./x.py build

test -f /usr/lib/libLLVM-3.9.so ||
  ln -sv /opt/llvm3/lib/libLLVM-3.9.so /usr/lib

DESTDIR=${FAKEROOT} ./x.py dist --install

#################
} # END OF FILE #
#################

