#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://sources.redhat.com/pub/docbook-tools/new-trials/SOURCES/sgml-common-0.6.3.tgz
          http://www.linuxfromscratch.org/patches/blfs/svn/sgml-common-0.6.3-manpage-1.patch"
MD5SUMLIST="103c9828f24820df86e55e7862e28974
            645f3c898abd270a9143036824ae121a"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../sgml-common-0.6.3-manpage-1.patch
autoreconf -f -i

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} docdir=/usr/share/doc install

# (*) Only to be run if upgrading
#install-catalog --remove /etc/sgml/sgml-ent.cat \
#    /usr/share/sgml/sgml-iso-entities-8879.1986/catalog
#
#install-catalog --remove /etc/sgml/sgml-docbook.cat \
#    /etc/sgml/sgml-ent.cat

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

install-catalog --add /etc/sgml/sgml-ent.cat \
    /usr/share/sgml/sgml-iso-entities-8879.1986/catalog

install-catalog --add /etc/sgml/sgml-docbook.cat \
    /etc/sgml/sgml-ent.cat

#################
} # END OF FILE #
#################

