#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://freedesktop.org/~hadess/shared-mime-info-1.8.tar.xz"
MD5SUMLIST="f6dcadce764605552fc956563efa058c"
REQUIRES="glib2 libxml2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make -j1

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Update the MIME database
update-mime-database /usr/share/mime

#################
} # END OF FILE #
#################

