#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.jedsoft.org/releases/slang/slang-2.3.1.tar.bz2"
MD5SUMLIST="bd46d1dc17a50c72004ad842829d7b1f"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-readline=gnu
make -j1

make DESTDIR=${FAKEROOT} install_doc_dir=/usr/share/doc/slang-2.3.1   \
     SLSH_DOC_DIR=/usr/share/doc/slang-2.3.1/slsh \
     install-all

chmod -v 755 ${FAKEROOT}/usr/lib/libslang.so.2.3.1 \
             ${FAKEROOT}/usr/lib/slang/v2/modules/*.so

#################
} # END OF FILE #
#################

