#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://sqlite.org/2017/sqlite-autoconf-3180000.tar.gz
          http://sqlite.org/2017/sqlite-doc-3180000.zip"
MD5SUMLIST="a6687a8ae1f66abc8df739aeadecfd0c
            3c0f877235e2f5e534dac6cde5ef51b0"
REQUIRES="unzip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

unzip -q ../sqlite-doc-3180000.zip

./configure --prefix=/usr --disable-static        \
            CFLAGS="-g -O2 -DSQLITE_ENABLE_FTS3=1 \
            -DSQLITE_ENABLE_COLUMN_METADATA=1     \
            -DSQLITE_ENABLE_UNLOCK_NOTIFY=1       \
            -DSQLITE_SECURE_DELETE=1              \
            -DSQLITE_ENABLE_DBSTAT_VTAB=1"
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/sqlite-3.18.0
cp -v -R sqlite-doc-3180000/* ${FAKEROOT}/usr/share/doc/sqlite-3.18.0

#################
} # END OF FILE #
#################

