#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-008.tar.xz"
MD5SUMLIST="2780b6ae21264c888f8f30fb2aab1259"
REQUIRES="libusb wget which"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/^usbids/ s:usb.ids:hwdata/&:' lsusb.py

./configure --prefix=/usr --datadir=/usr/share/hwdata
make

make DESTDIR=${FAKEROOT} install

install -dm755 ${FAKEROOT}/usr/share/hwdata/
wget http://www.linux-usb.org/usb.ids -O ${FAKEROOT}/usr/share/hwdata/usb.ids

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

wget http://www.linux-usb.org/usb.ids -O /usr/share/hwdata/usb.ids

#################
} # END OF FILE #
#################

