#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.x.org/pub/individual/util/util-macros-1.19.1.tar.bz2"
MD5SUMLIST="6e76e546a4e580f15cebaf8019ef1625"
REQUIRES="xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

