#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.debian.org/debian/pool/main/w/whois/whois_5.2.15.tar.xz"
MD5SUMLIST="ef99ddbb9105106aa72f7485960d8a10"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make BASEDIR=${FAKEROOT} prefix=/usr install-whois
make BASEDIR=${FAKEROOT} prefix=/usr install-mkpasswd
make BASEDIR=${FAKEROOT} prefix=/usr install-pos

#################
} # END OF FILE #
#################

