#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20170212-2245-stable.tar.bz2"
MD5SUMLIST="127ade6bafce9f6d522e1c214156f4ed"
REQUIRES="yasm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --enable-shared \
            --disable-cli
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

