#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://bitbucket.org/multicoreware/x265/downloads/x265_2.4.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/x265_2.4-enable_static-1.patch"
MD5SUMLIST="ab0986aa5c4465b874de94095b0d0cae
            98f7b38e7b918e95ed3becdf4e81bd61"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../x265_2.4-enable_static-1.patch

mkdir bld
cd    bld

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DENABLE_STATIC=OFF         \
      ../source

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

