#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.x.org/pub/individual/app/iceauth-1.0.7.tar.bz2
          https://www.x.org/pub/individual/app/luit-1.1.1.tar.bz2
          https://www.x.org/pub/individual/app/mkfontdir-1.0.7.tar.bz2
          https://www.x.org/pub/individual/app/mkfontscale-1.1.2.tar.bz2
          https://www.x.org/pub/individual/app/sessreg-1.1.1.tar.bz2
          https://www.x.org/pub/individual/app/setxkbmap-1.3.1.tar.bz2
          https://www.x.org/pub/individual/app/smproxy-1.0.6.tar.bz2
          https://www.x.org/pub/individual/app/x11perf-1.6.0.tar.bz2
          https://www.x.org/pub/individual/app/xauth-1.0.10.tar.bz2
          https://www.x.org/pub/individual/app/xbacklight-1.2.1.tar.bz2
          https://www.x.org/pub/individual/app/xcmsdb-1.0.5.tar.bz2
          https://www.x.org/pub/individual/app/xcursorgen-1.0.6.tar.bz2
          https://www.x.org/pub/individual/app/xdpyinfo-1.3.2.tar.bz2
          https://www.x.org/pub/individual/app/xdriinfo-1.0.5.tar.bz2
          https://www.x.org/pub/individual/app/xev-1.2.2.tar.bz2
          https://www.x.org/pub/individual/app/xgamma-1.0.6.tar.bz2
          https://www.x.org/pub/individual/app/xhost-1.0.7.tar.bz2
          https://www.x.org/pub/individual/app/xinput-1.6.2.tar.bz2
          https://www.x.org/pub/individual/app/xkbcomp-1.3.1.tar.bz2
          https://www.x.org/pub/individual/app/xkbevd-1.1.4.tar.bz2
          https://www.x.org/pub/individual/app/xkbutils-1.0.4.tar.bz2
          https://www.x.org/pub/individual/app/xkill-1.0.4.tar.bz2
          https://www.x.org/pub/individual/app/xlsatoms-1.1.2.tar.bz2
          https://www.x.org/pub/individual/app/xlsclients-1.1.3.tar.bz2
          https://www.x.org/pub/individual/app/xmessage-1.0.4.tar.bz2
          https://www.x.org/pub/individual/app/xmodmap-1.0.9.tar.bz2
          https://www.x.org/pub/individual/app/xpr-1.0.4.tar.bz2
          https://www.x.org/pub/individual/app/xprop-1.2.2.tar.bz2
          https://www.x.org/pub/individual/app/xrandr-1.5.0.tar.bz2
          https://www.x.org/pub/individual/app/xrdb-1.1.0.tar.bz2
          https://www.x.org/pub/individual/app/xrefresh-1.0.5.tar.bz2
          https://www.x.org/pub/individual/app/xset-1.2.3.tar.bz2
          https://www.x.org/pub/individual/app/xsetroot-1.1.1.tar.bz2
          https://www.x.org/pub/individual/app/xvinfo-1.1.3.tar.bz2
          https://www.x.org/pub/individual/app/xwd-1.0.6.tar.bz2
          https://www.x.org/pub/individual/app/xwininfo-1.1.3.tar.bz2
          https://www.x.org/pub/individual/app/xwud-1.0.4.tar.bz2"
MD5SUMLIST="25dab02f8e40d5b71ce29a07dc901b8c
            c4a3664e08e5a47c120ff9263ee2f20c
            18c429148c96c2079edda922a2b67632
            9bdd6ebfa62b1bbd474906ac86a40fd8
            e475167a892b589da23edf8edf8c942d
            2c47a1b8e268df73963c4eb2316b1a89
            3a93d9f0859de5d8b65a68a125d48f6a
            f0b24e4d8beb622a419e8431e1c03cd7
            f3f76cb10f69b571c43893ea6a634aa4
            0066f23f69ca3ef62dcaeb74a87fdc48
            9956d751ea3ae4538c3ebd07f70736a0
            b58a87e6cd7145c70346adad551dba48
            8809037bd48599af55dad81c508b6b39
            fceddaeb08e32e027d12a71490665866
            249bdde90f01c0d861af52dc8fec379e
            90b4305157c2b966d5180e2ee61262be
            f5d490738b148cb7f2fe760f40f92516
            6a889412eff2e3c1c6bb19146f6fe84c
            a4d8353daf6cb0a9c47379b7413c42c6
            c747faf1f78f5a5962419f8bdd066501
            502b14843f610af977dffc6cbf2102d5
            0ae6bc2a8d3af68e9c76b1a6ca5f7a78
            5dcb6e6c4b28c8d7aeb45257f5a72a7d
            9fbf6b174a5138a61738a42e707ad8f5
            2dd5ae46fa18abc9331bc26250a25005
            723f02d3a5f98450554556205f0a9497
            6101f04731ffd40803df80eca274ec4b
            fae3d2fda07684027a643ca783d595cc
            ebffac98021b8f1dc71da0c1918e9b57
            b54c7e3e53b4f332d41ed435433fbda0
            a896382bc53ef3e149eaf9b13bc81d42
            dcd227388b57487d543cab2fd7a602d7
            7211b31ec70631829ebae9460999aa0b
            558360176b718dee3c39bc0648c0d10c
            6b5d48464c5f366e91efd08b62b12d94
            b777bafb674555e48fd8437618270931
            3025b152b4f13fdffd0c46d0be587be6"
REQUIRES="libpng mesa xbitmaps xcb-util xorg-env"
TAGS="multi"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case $(basename "$PWD") in
  luit-[0-9]* )
    sed -i -e "/D_XOPEN/s/5/6/" configure
  ;;
esac

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

rm -f ${FAKEROOT}${XORG_PREFIX}/bin/xkeystone

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) Properly register all installed fonts for X11
mkdir -p /usr/share/fonts/X11
pushd /usr/share/fonts/X11
for dir in $(ls); do
    pushd ${dir}

    rm -f fonts.scale fonts.dir
    mkfontscale
    mkfontdir

    popd
done
popd

#################
} # END OF FILE #
#################

