#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.x.org/pub/individual/driver/xf86-video-ati-7.9.0.tar.bz2"
MD5SUMLIST="bf3dfdae23879bdc0c8a7b955572ad90"
REQUIRES="xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

install -v -m644 conf/10-radeon.conf \
  ${FAKEROOT}${XORG_PREFIX}/share/X11/xorg.conf.d

#################
} # END OF FILE #
#################

