#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.x.org/pub/individual/driver/xf86-video-nouveau-1.0.14.tar.bz2"
MD5SUMLIST="c57c89e1a3c9bc319d26f2e11c80e7fb"
REQUIRES="xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

