#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/linuxwacom/xf86-input-wacom-0.34.2.tar.bz2"
MD5SUMLIST="bfc2bb315210f735bcdb9f7887c9d609"
REQUIRES="xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --with-systemd-unit-dir=no
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

