#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/BLFS/xf86-video-intel/xf86-video-intel-20170216.tar.xz"
MD5SUMLIST="797c06a33bd1b3fb5a33468fbc84518d"
REQUIRES="xcb-util xorg-env xorg-server"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --enable-kms-only --enable-uxa
make

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/share/man/man4/intel-virtual-output.4 \
      ${FAKEROOT}/usr/share/man/man1/intel-virtual-output.1
sed -i '/\.TH/s/4/1/' ${FAKEROOT}/usr/share/man/man1/intel-virtual-output.1

#################
} # END OF FILE #
#################

