#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.x.org/pub/individual/font/font-util-1.3.1.tar.bz2
          https://www.x.org/pub/individual/font/encodings-1.0.4.tar.bz2
          https://www.x.org/pub/individual/font/font-alias-1.0.3.tar.bz2
          https://www.x.org/pub/individual/font/font-adobe-utopia-type1-1.0.4.tar.bz2
          https://www.x.org/pub/individual/font/font-bh-ttf-1.0.3.tar.bz2
          https://www.x.org/pub/individual/font/font-bh-type1-1.0.3.tar.bz2
          https://www.x.org/pub/individual/font/font-ibm-type1-1.0.3.tar.bz2
          https://www.x.org/pub/individual/font/font-misc-ethiopic-1.0.3.tar.bz2
          https://www.x.org/pub/individual/font/font-xfree86-type1-1.0.4.tar.bz2"
MD5SUMLIST="23756dab809f9ec5011bb27fb2c3c7d6
            0f2d6546d514c5cc4ecf78a60657a5c1
            6d25f64796fef34b53b439c2e9efa562
            fcf24554c348df3c689b91596d7f9971
            e8ca58ea0d3726b94fe9f2c17344be60
            53ed9a42388b7ebb689bdfc374f96a22
            bfb2593d2102585f45daa960f43cb3c4
            6306c808f7d7e7d660dfb3859f9091d2
            3eeb3fb44690b477d510bbd8f86cf5aa"
REQUIRES="xcursor-themes xorg-env"
TAGS="multi"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

install -v -d -m755 ${FAKEROOT}/usr/share/fonts
ln -svfn $XORG_PREFIX/share/fonts/X11/OTF ${FAKEROOT}/usr/share/fonts/X11-OTF
ln -svfn $XORG_PREFIX/share/fonts/X11/TTF ${FAKEROOT}/usr/share/fonts/X11-TTF

#################
} # END OF FILE #
#################

