#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://xcb.freedesktop.org/dist/xcb-util-wm-0.4.1.tar.bz2"
MD5SUMLIST="87b19a1cd7bfcb65a24e36c300e03129"
REQUIRES="libxcb xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

