#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://portland.freedesktop.org/download/xdg-utils-1.1.1.tar.gz"
MD5SUMLIST="2d0aec6037769a5f138ff404b1bb4b15"
REQUIRES="links x7app xmlto"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --mandir=/usr/share/man
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

