#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://xorg.freedesktop.org/archive/individual/data/xkeyboard-config/xkeyboard-config-2.20.tar.bz2"
MD5SUMLIST="1f68886339116ae3877052204c9b9b88"
REQUIRES="x7lib xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure $XORG_CONFIG --with-xkb-rules-symlink=xorg
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

