#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://invisible-island.net/xterm/xterm-327.tgz"
MD5SUMLIST="3c32e931adcad44e64e57892e75d9e02"
REQUIRES="dejavu-fonts x7app xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/v0/{n;s/new:/new:kb=^?:/}' termcap
printf '\tkbs=\\177,\n' >> terminfo

TERMINFO=/usr/share/terminfo \
./configure $XORG_CONFIG     \
    --with-app-defaults=/etc/X11/app-defaults

make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} install-ti

cat >> ${FAKEROOT}/etc/X11/app-defaults/XTerm << "EOF"
*VT100*locale: true
*VT100*faceName: Monospace
*VT100*faceSize: 10
*backarrowKeyIsErase: true
*ptyInitialErase: true
EOF

#################
} # END OF FILE #
#################

