#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/diffutils/diffutils-3.5.tar.xz"
MD5SUMLIST="569354697ff1cfc9a9de3781361015fa"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's:= @mkdir_p@:= /bin/mkdir -p:' po/Makefile.in.in

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

