#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/glibc/glibc-2.25.tar.xz
          http://www.iana.org/time-zones/repository/releases/tzdata2017b.tar.gz
          http://www.linuxfromscratch.org/patches/lfs/development/glibc-2.25-fhs-1.patch"
MD5SUMLIST="1496c3bf41adf9db0ebd0af01f202eed
            50dc0dc50c68644c1f70804f2e7a1625
            9a5997c3452909b1769918c759eff8a2"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../glibc-2.25-fhs-1.patch

case $(uname -m) in
    x86) ln -s ld-linux.so.2 ${FAKEROOT}/lib/ld-lsb.so.3
    ;;
    x86_64) ln -s ../lib/ld-linux-x86-64.so.2 ${FAKEROOT}/lib64
            ln -s ../lib/ld-linux-x86-64.so.2 ${FAKEROOT}/lib64/ld-lsb-x86-64.so.3
    ;;
esac

mkdir -v build
cd       build

../configure --prefix=/usr                   \
             --enable-kernel=2.6.32          \
             --enable-obsolete-rpc           \
             --enable-stack-protector=strong \
             libc_cv_slibdir=/lib

make

touch ${FAKEROOT}/etc/ld.so.conf

make install_root=${FAKEROOT} install

cp -v ../nscd/nscd.conf ${FAKEROOT}/etc/nscd.conf
mkdir -pv ${FAKEROOT}/var/cache/nscd

make install_root=${FAKEROOT} localedata/install-locales

cat > ${FAKEROOT}/etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

tar -xf ../../tzdata2017b.tar.gz

ZONEINFO=${FAKEROOT}/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
          asia australasia backward pacificnew systemv; do
    /tools/sbin/zic -L /dev/null   -d $ZONEINFO       -y "sh yearistype.sh" ${tz}
    /tools/sbin/zic -L /dev/null   -d $ZONEINFO/posix -y "sh yearistype.sh" ${tz}
    /tools/sbin/zic -L leapseconds -d $ZONEINFO/right -y "sh yearistype.sh" ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
/tools/sbin/zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

cat > ${FAKEROOT}/etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib

EOF

cat >> ${FAKEROOT}/etc/ld.so.conf << "EOF"
# Add an include directory
include /etc/ld.so.conf.d/*.conf

EOF
mkdir -pv ${FAKEROOT}/etc/ld.so.conf.d

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

# (*) This will run 'tzselect' to determine your timezone when installing your
#     system, unless you have set up the TZ variable in 'install.conf'.
if [ "${LFSCRIPT_INSTALL}" == "true" ]; then
    [ "${TZ}" == "" ] && TZ="$(tzselect)"
else
    TZ="UTC"
fi
#tzselect

# (*) This will set the time zone to the one selected earlier.
cp -v /usr/share/zoneinfo/${TZ} /etc/localtime

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

mkdir -v build
cd       build

../configure                             \
      --prefix=/tools                    \
      --host=$LFS_TGT                    \
      --build=$(../scripts/config.guess) \
      --enable-kernel=2.6.32             \
      --with-headers=/tools/include      \
      libc_cv_forced_unwind=yes          \
      libc_cv_c_cleanup=yes

make

make install

#################
} # END OF FILE #
#################

