#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/sed/sed-4.4.tar.xz"
MD5SUMLIST="e0c583d4c380059abd818cd540fe6938"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/usr/tools/'       build-aux/help2man
sed -i 's/panic-tests.sh//' Makefile.in

./configure --prefix=/usr --bindir=/bin

make
make html

make DESTDIR=${FAKEROOT} install
install -d -m755           ${FAKEROOT}/usr/share/doc/sed-4.4
install -m644 doc/sed.html ${FAKEROOT}/usr/share/doc/sed-4.4

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

