#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.abisource.com/downloads/abiword/3.0.2/source/abiword-3.0.2.tar.gz
          http://www.abisource.com/downloads/abiword/3.0.2/source/abiword-docs-3.0.2.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/abiword-3.0.2-gtk3_22_render_fix-1.patch"
MD5SUMLIST="cda6dd58c747c133b421cc7eb18f5796
            dontverify
            dontverify"
REQUIRES="boost fribidi goffice010 wv"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../abiword-3.0.2-gtk3_22_render_fix-1.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

tar -xf ../abiword-docs-3.0.2.tar.gz
cd abiword-docs-3.0.1
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

install -v -m750 -d ${FAKEROOT}/etc/skel/.AbiSuite/templates
install -v -m640    ${FAKEROOT}/usr/share/abiword-3.0/templates/normal.awt-<lang> \
                    ${FAKEROOT}/etc/skel/.AbiSuite/templates/normal.awt

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ls /usr/share/abiword-3.0/templates

#################
} # END OF FILE #
#################

