#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/acpid2/acpid-2.0.28.tar.xz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="0432407b5ff75ae8e08afb43052fde2b
            b4f1623b69c67f10e67ca610ceee56b4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --docdir=/usr/share/doc/acpid-2.0.28
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/etc/acpi/events

cp -r samples ${FAKEROOT}/usr/share/doc/acpid-2.0.28

cat > ${FAKEROOT}/etc/acpi/events/lid << "EOF"
event=button/lid
action=/etc/acpi/lid.sh
EOF

cat > ${FAKEROOT}/etc/acpi/lid.sh << "EOF"
#!/bin/sh
/bin/grep -q open /proc/acpi/button/lid/LID/state && exit 0
/usr/sbin/pm-suspend
EOF
chmod +x ${FAKEROOT}/etc/acpi/lid.sh

includeBootscript acpid

#################
} # END OF FILE #
#################

