#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.1.tar.bz2"
MD5SUMLIST="69f9f3e2de3c97fc71d496e91e271fe5"
REQUIRES="alsa-lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

