#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.alsa-project.org/pub/oss-lib/alsa-oss-1.0.28.tar.bz2"
MD5SUMLIST="91f57e8cee1ad4cc956caa8b62ac5d43"
REQUIRES="alsa-lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

