#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://archive.apache.org/dist/ant/source/apache-ant-1.10.1-src.tar.xz"
MD5SUMLIST="ebecbe7488c624b06bc6a264a3a7c4ec"
REQUIRES="glib2 java-bin openjdk postlfs"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cp -v ../junit-4.11.jar \
      ../hamcrest-core-1.3.jar lib/optional

./build.sh -Ddist.dir=/opt/ant-1.10.1 dist
ln -v -sfn ant-1.10.1 ${FAKEROOT}/opt/ant

cat > ${FAKEROOT}/etc/profile.d/ant.sh << EOF
# Begin ${FAKEROOT}/etc/profile.d/ant.sh

pathappend /opt/ant/bin
export ANT_HOME=/opt/ant

# End ${FAKEROOT}/etc/profile.d/ant.sh
EOF

#################
} # END OF FILE #
#################

