#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://archive.apache.org/dist/httpd/httpd-2.4.25.tar.bz2
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/httpd-2.4.25-blfs_layout-1.patch"
MD5SUMLIST="2826f49619112ad5813c0be5afcc7ddb
            b4f1623b69c67f10e67ca610ceee56b4
            dontverify"
REQUIRES="apr-util pcre"
TAGS="preinst"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../httpd-2.4.25-blfs_layout-1.patch

sed '/dir.*CFG_PREFIX/s@^@#@' -i support/apxs.in

./configure --enable-authnz-fcgi                            \
            --enable-layout=BLFS                            \
            --enable-mods-shared="all cgi"                  \
            --enable-mpms-shared=all                        \
            --enable-suexec=shared                          \
            --with-apr=/usr/bin/apr-1-config                \
            --with-apr-util=/usr/bin/apu-1-config           \
            --with-suexec-bin=/usr/lib/httpd/suexec         \
            --with-suexec-caller=apache                     \
            --with-suexec-docroot=/srv/www                  \
            --with-suexec-logfile=/var/log/httpd/suexec.log \
            --with-suexec-uidmin=100                        \
            --with-suexec-userdir=public_html
make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/sbin/suexec ${FAKEROOT}/usr/lib/httpd/suexec
chgrp apache           ${FAKEROOT}/usr/lib/httpd/suexec
chmod 4754             ${FAKEROOT}/usr/lib/httpd/suexec

chown -v -R apache:apache ${FAKEROOT}/srv/www

includeBootscript httpd

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 25 apache
useradd -c "Apache Server" -d /srv/www -g apache \
        -s /bin/false -u 25 apache

#################
} # END OF FILE #
#################

