#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.gimp.org/pub/babl/0.1/babl-0.1.24.tar.bz2"
MD5SUMLIST="c32245f90a0b59e4714b546308d2ee34"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-docs
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/gtk-doc/html/babl/graphics
install -v -m644 docs/*.{css,html} ${FAKEROOT}/usr/share/gtk-doc/html/babl
install -v -m644 docs/graphics/*.{html,png,svg} ${FAKEROOT}/usr/share/gtk-doc/html/babl/graphics

#################
} # END OF FILE #
#################

