#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://pawsa.fedorapeople.org/balsa/balsa-2.5.3.tar.bz2"
MD5SUMLIST="d02bc62af34c4d1b0c1f6cfb4efff8db"
REQUIRES="aspell enchant gmime libesmtp rarian"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr            \
            --sysconfdir=/etc        \
            --localstatedir=/var/lib \
            --without-html-widget    \
            --without-libnotify
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

