#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/plk/biber/archive/v2.7.tar.gz"
MD5SUMLIST="4956fbf23546b6325647b6c81b2b4bea"
REQUIRES="perl-autovivification perl-business-isbn perl-business-ismn perl-business-issn perl-class-accessor perl-data-compare perl-data-dump perl-data-uniqid perl-datetime-calendar-julian perl-datetime-format-builder perl-encode-eucjpascii perl-encode-hanextra perl-encode-jis2k perl-file-slurp perl-ipc-run3 perl-lingua-translit perl-list-allutils perl-list-moreutils perl-log-log4perl perl-lwp-protocol-https perl-module-build perl-regexp-common perl-sort-key perl-text-bibtex perl-text-csv perl-text-roman perl-unicode-collate perl-unicode-linebreak perl-xml-libxml-simple perl-xml-libxslt perl-xml-writer texlive tl-installer"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

perl ./Build.PL
./Build

tar -xf ../biblatex-3.7.tds.tgz -C ${FAKEROOT}/opt/texlive/2016/texmf-dist
texhash
./Build install

#################
} # END OF FILE #
#################

