#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.bennewitz.com/bluefish/stable/source/bluefish-2.2.10.tar.bz2"
MD5SUMLIST="06cc710505856cb328444d834f5e9666"
REQUIRES="gtk+2 gtk+3"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/bluefish-2.2.10
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache -t -f --include-image-data /usr/share/icons/hicolor
update-desktop-database

#################
} # END OF FILE #
#################

