#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/brasero/3.12/brasero-3.12.1.tar.xz"
MD5SUMLIST="216691249053448a9f2b4ee5e118ce72"
REQUIRES="gst10-plugins-base itstool libcanberra libnotify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                \
            --enable-compile-warnings=no \
            --enable-cxx-warnings=no
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

