#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/frameworks/5.31/breeze-icons-5.31.0.tar.xz"
MD5SUMLIST="f16a9b1a901700ecd0790e3d80ae32d4"
REQUIRES="extra-cmake-modules qt5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DBUILD_TESTING=OFF         \
      -Wno-dev ..

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

