#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/libcheck/check/releases/download/0.11.0/check-0.11.0.tar.gz"
MD5SUMLIST="9b90522b31f5628c2e0f55dda348e558"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} docdir=/usr/share/doc/check-0.11.0 install

#################
} # END OF FILE #
#################

