#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://alioth.debian.org/frs/download.php/latestfile/813/chrpath-0.16.tar.gz"
MD5SUMLIST="2bf8d1d1ee345fc8a7915576f5649982"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} docdir=/usr/share/doc/chrpath-0.16 install

#################
} # END OF FILE #
#################

