#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://ftp.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.7.tar.bz2"
MD5SUMLIST="af3ae1d27aca624c4daac5bf3eb0d4c1"
REQUIRES="talloc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

autoreconf -fiv
./configure --prefix=/usr \
            --disable-pam \
            --disable-systemd
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

