#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/cracklib/cracklib/releases/download/cracklib-2.9.6/cracklib-2.9.6.tar.gz
          https://github.com/cracklib/cracklib/releases/download/cracklib-2.9.6/cracklib-words-2.9.6.gz"
MD5SUMLIST="c52f463585d85924b28cdc1e373ae06d
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/skipping/d' util/packer.c

./configure --prefix=/usr    \
            --disable-static \
            --with-default-dict=/lib/cracklib/pw_dict
make

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/lib/libcrack.so.* ${FAKEROOT}/lib
ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/libcrack.so) ${FAKEROOT}/usr/lib/libcrack.so

install -v -m644 -D    ../cracklib-words-2.9.6.gz \
                         ${FAKEROOT}/usr/share/dict/cracklib-words.gz

gunzip -v                ${FAKEROOT}/usr/share/dict/cracklib-words.gz
ln -v -sf cracklib-words ${FAKEROOT}/usr/share/dict/words
echo $(hostname) >>      ${FAKEROOT}/usr/share/dict/cracklib-extra-words
install -v -m755 -d      ${FAKEROOT}/lib/cracklib

create-cracklib-dict     ${FAKEROOT}/usr/share/dict/cracklib-words \
                         ${FAKEROOT}/usr/share/dict/cracklib-extra-words

make test

#################
} # END OF FILE #
#################

