#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.openprinting.org/download/cups-filters/cups-filters-1.13.4.tar.xz"
MD5SUMLIST="a288a63ca44ad6e776cf1e86a457f836"
REQUIRES="cups glib2 gs ijs lcms2 mupdf poppler qpdf"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure                             \
        --prefix=/usr                   \
        --sysconfdir=/etc               \
        --localstatedir=/var            \
        --without-rcdir                 \
        --disable-static                \
        --disable-avahi                 \
        --docdir=/usr/share/doc/cups-filters-1.13.4
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

