#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.26.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/cyrus-sasl-2.1.26-fixes-3.patch"
MD5SUMLIST="a7f4e5e559a0e37b3ffc438c9456e425
            b4f1623b69c67f10e67ca610ceee56b4
            dontverify"
REQUIRES="openssl"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../cyrus-sasl-2.1.26-fixes-3.patch
autoreconf -fi

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --enable-auth-sasldb \
            --with-dbpath=/var/lib/sasl/sasldb2 \
            --with-saslauthd=/var/run/saslauthd
make

make DESTDIR=${FAKEROOT} install
install -v -dm755 ${FAKEROOT}/usr/share/doc/cyrus-sasl-2.1.26
install -v -m644  doc/{*.{html,txt,fig},ONEWS,TODO} \
    saslauthd/LDAP_SASLAUTHD ${FAKEROOT}/usr/share/doc/cyrus-sasl-2.1.26
install -v -dm700 ${FAKEROOT}/var/lib/sasl

includeBootscript saslauthd

#################
} # END OF FILE #
#################

