#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://ftp.gnu.org/pub/gnu/dejagnu/dejagnu-1.6.tar.gz"
MD5SUMLIST="1fdc2eb0d592c4f89d82d24dfdf02f0b"
REQUIRES="expect"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
makeinfo --html --no-split -o doc/dejagnu.html doc/dejagnu.texi
makeinfo --plaintext       -o doc/dejagnu.txt  doc/dejagnu.texi

make DESTDIR=${FAKEROOT} install
install -v -dm755   ${FAKEROOT}/usr/share/doc/dejagnu-1.6
install -v -m644    doc/dejagnu.{html,txt} \
                    ${FAKEROOT}/usr/share/doc/dejagnu-1.6

#################
} # END OF FILE #
#################

