#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://ftp.gnu.org/pub/gnu/emacs/emacs-25.2.tar.xz"
MD5SUMLIST="06442d867158754bdde793eca420ca49"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --localstatedir=/var
make

make DESTDIR=${FAKEROOT} install
chown -v -R root:root ${FAKEROOT}/usr/share/emacs/25.2

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache -t -f --include-image-data /usr/share/icons/hicolor
update-desktop-database

#################
} # END OF FILE #
#################

