#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/BLFS/epdfview/epdfview-0.1.8.tar.bz2
          http://www.linuxfromscratch.org/patches/blfs/svn/epdfview-0.1.8-fixes-2.patch"
MD5SUMLIST="e50285b01612169b2594fea375f53ae4
            dontverify"
REQUIRES="gtk+2 poppler"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../epdfview-0.1.8-fixes-2.patch
./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

for size in 24 32 48; do
  ln -svf ../../../../epdfview/pixmaps/icon_epdfview-$size.png \
          /usr/share/icons/hicolor/${size}x${size}/apps
done
unset size

update-desktop-database
gtk-update-icon-cache -t -f --include-image-data /usr/share/icons/hicolor

#################
} # END OF FILE #
#################

