#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/epiphany/3.22/epiphany-3.22.6.tar.xz"
MD5SUMLIST="e08762c6bb01c4d291b3d22c7adb1a65"
REQUIRES="avahi gcr gnome-desktop iso-codes libnotify libwnck webkitgtk"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

make -k check

#################
} # END OF FILE #
#################

