#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/frameworks/5.31/extra-cmake-modules-5.31.0.tar.xz"
MD5SUMLIST="74d7c29138168f9a62fe475705c0b351"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/"lib64"/s/64//' kde-modules/KDEInstallDirs.cmake

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

