#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/fetchmail/fetchmail-6.3.26.tar.xz"
MD5SUMLIST="61b66faad044afa26e142bb1791aa2b3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --with-ssl --enable-fallback=procmail
make

make DESTDIR=${FAKEROOT} install

# (*) Example configuration
#cat > ~/.fetchmailrc << "EOF"
#set logfile /var/log/fetchmail.log
#set no bouncemail
#set postmaster root
#
#poll SERVERNAME :
#    user <username> pass <password>;
#    mda "/usr/bin/procmail -f %F -d %T";
#EOF
#
#chmod -v 0600 ~/.fetchmailrc

#################
} # END OF FILE #
#################

