#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/file-roller/3.22/file-roller-3.22.3.tar.xz"
MD5SUMLIST="a95f662fd9669eaca32a855240faffdd"
REQUIRES="gtk+3 itstool"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr         \
            --disable-packagekit  \
            --disable-static
make

make DESTDIR=${FAKEROOT} install
chmod -v 0755 ${FAKEROOT}/usr/libexec/file-roller/isoinfo.sh

#################
} # END OF FILE #
#################

