#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/fontforge/fontforge/releases/download/20161005/fontforge-dist-20161004.tar.gz"
MD5SUMLIST="15c0d785112dc7f1884df357f79def47"
REQUIRES="freetype2 glib2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --enable-gtk2-use \
            --disable-static  \
            --docdir=/usr/share/doc/fontforge-20161004
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

