#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://archive.apache.org/dist/xmlgraphics/fop/source/fop-2.1-src.tar.gz
          http://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-amd64.tar.gz
          http://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-i586.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/fop-2.1-listNPE-1.patch"
MD5SUMLIST="13b5b497dfb0ba8a01093dfc1a89d106
            dontverify
            dontverify
            dontverify"
REQUIRES="apache-ant"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case `uname -m` in
  i?86)
    tar -xf ../jai-1_1_3-lib-linux-i586.tar.gz
    cp -v jai-1_1_3/lib/{jai*,mlibwrapper_jai.jar} $JAVA_HOME/jre/lib/ext/
    cp -v jai-1_1_3/lib/libmlib_jai.so             $JAVA_HOME/jre/lib/i386/
    ;;

  x86_64)
    tar -xf ../jai-1_1_3-lib-linux-amd64.tar.gz
    cp -v jai-1_1_3/lib/{jai*,mlibwrapper_jai.jar} $JAVA_HOME/jre/lib/ext/
    cp -v jai-1_1_3/lib/libmlib_jai.so             $JAVA_HOME/jre/lib/amd64/
    ;;
esac

sed -i '\@</javad@i\
<arg value="-Xdoclint:none"/>\
<arg value="--allow-script-in-comments"/>' build.xml

patch -Np1 -i ../fop-2.1-listNPE-1.patch

ant compile
ant jar-main
ant javadocs
mv build/javadocs .

install -v -d -m755 -o root -g root          ${FAKEROOT}/opt/fop-2.1
cp -v  KEYS LICENSE NOTICE README            ${FAKEROOT}/opt/fop-2.1
cp -vR build conf examples fop* javadocs lib ${FAKEROOT}/opt/fop-2.1

ln -v -sf fop-2.1 ${FAKEROOT}/opt/fop

cat > ${FAKEROOT}/etc/skel/.foprc << "EOF"
FOP_OPTS="-Xmx<RAM_Installed>m"
FOP_HOME="/opt/fop"
EOF

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

FOP_OPTS="-Xmx768m"

#################
} # END OF FILE #
#################

