#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/libfuse/libfuse/releases/download/fuse-3.0.1/fuse-3.0.1.tar.gz"
MD5SUMLIST="8fbe5e8293deaa7a2072f30dbdc29669"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --exec-prefix=/  \
            --with-pkgconfigdir=/usr/lib/pkgconfig \
            INIT_D_PATH=/tmp/init.d
make

make DESTDIR=${FAKEROOT} install
rm -v ${FAKEROOT}/lib/libfuse3.{so,la}
ln -sfv ../../lib/libfuse3.so.3 ${FAKEROOT}/usr/lib/libfuse3.so

rm -rf  ${FAKEROOT}/tmp/init.d

install -v -m755 -d ${FAKEROOT}/usr/share/doc/fuse-3.0.1
install -v -m644    doc/{README.NFS,kernel.txt} \
                    ${FAKEROOT}/usr/share/doc/fuse-3.0.1
cp -Rv doc/html ${FAKEROOT}/usr/share/doc/fuse-3.0.1

cat > ${FAKEROOT}/etc/fuse.conf << "EOF"
# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#
#mount_max = 1000

# Allow non-root users to specify the 'allow_other' or 'allow_root'
# mount options.
#
#user_allow_other
EOF

#################
} # END OF FILE #
#################

