#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftpmirror.gnu.org/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2"
MD5SUMLIST="677a7623c7ef6ab99881bc4e048debb6"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DESTDIR=${FAKEROOT} ins-all prefix=/opt/gnat

PATH_HOLD=$PATH
export PATH=/opt/gnat/bin:$PATH_HOLD

find ${FAKEROOT}/opt/gnat -name ld -exec mv -v {} {}.old \;
find ${FAKEROOT}/opt/gnat -name as -exec mv -v {} {}.old \;

#################
} # END OF FILE #
#################

