#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftpmirror.gnu.org/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2"
MD5SUMLIST="677a7623c7ef6ab99881bc4e048debb6"
REQUIRES="unzip which zip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac

sed -i 's/\(install.*:\) install-.*recursive/\1/' libffi/Makefile.in
sed -i 's/\(install-data-am:\).*/\1/'             libffi/include/Makefile.in
sed -i 's/absolute/file normalize/' libjava/testsuite/lib/libjava.exp
sed -i 's/major.*1000.*minor/major/' gcc/java/decl.c

cp ../ecj-4.9.jar ./ecj.jar

mkdir build
cd    build

../configure                     \
    --prefix=/usr                \
    --disable-multilib           \
    --with-system-zlib           \
    --disable-bootstrap          \
    --enable-java-home           \
    --with-jvm-root-dir=/opt/gcj \
    --with-antlr-jar=$(pwd)/../../antlr-4.6-complete.jar \
    --enable-languages=java
make

ulimit -s 32768
make -k check

../contrib/test_summary

make DESTDIR=${FAKEROOT} install

mkdir -pv ${FAKEROOT}/usr/share/gdb/auto-load/usr/lib
mv -v ${FAKEROOT}/usr/lib/*gdb.py ${FAKEROOT}/usr/share/gdb/auto-load/usr/lib

chown -v -R root:root \
    ${FAKEROOT}/usr/lib/gcc/*linux-gnu/6.3.0/include{,-fixed}

gcj -o ecj ../../ecj-4.9.jar \
    --main=org.eclipse.jdt.internal.compiler.batch.Main
mv ecj ${FAKEROOT}/usr/bin
ln -sfv ../../../usr/bin/ecj ${FAKEROOT}/opt/gcj/bin/javac

#################
} # END OF FILE #
#################

