#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/GConf/3.2/GConf-3.2.6.tar.xz"
MD5SUMLIST="2b16996d0e4b112856ee5c59130e822c"
REQUIRES="dbus-glib gtk+2 libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --disable-orbit \
            --disable-static
make

make DESTDIR=${FAKEROOT} install
ln -s gconf.xml.defaults ${FAKEROOT}/etc/gconf/gconf.xml.system

#################
} # END OF FILE #
#################

