#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="aalib babl exiv2 fontconfig freetype2 fribidi gegl giflib graphite2 harfbuzz ijs jasper lcms lcms2 libexif libjpeg-turbo libmng libpng libraw librsvg libtiff libwebp newt opencv openjpeg openjpeg2 pixman poppler qpdf"
TAGS="group"

