#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="apache-ant autoconf213 cargo check clisp cmake dejagnu doxygen elfutils expect gc gcc gcc-ada gcc-java gdb general-prog-python-modules git guile java junit librep llvm llvm3 lua mercurial nasm ninja npapi-sdk openjdk python2 python3 ruby rust scons slang subversion swig tcl tk vala valgrind yasm"
TAGS="group"

