#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="acpid at autofs colord cpio dbus fcron gpm hdparm initdtools lm_sensors logrotate mc modemmanager obex-data-server p7zip pax pciutils pm-utils raptor rasqal redland sg3_utils sysstat udisks udisks2 unrar unzip upower usbutils which zip"
TAGS="group"

