#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/giflib/giflib-5.1.4.tar.bz2"
MD5SUMLIST="2c171ced93c0e83bb09e6ccad8e3ba2b"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

find doc \( -name Makefile\* -o -name \*.1 \
         -o -name \*.xml \) -exec rm -v {} \;

install -v -dm755 ${FAKEROOT}/usr/share/doc/giflib-5.1.4
cp -v -R doc/* ${FAKEROOT}/usr/share/doc/giflib-5.1.4

#################
} # END OF FILE #
#################

