#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.gimp.org/pub/gimp/v2.8/gimp-2.8.20.tar.bz2"
MD5SUMLIST="d405640c426b234d6efc36fb4f5bae57"
REQUIRES="gegl gtk+2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/gegl/s/2/3/' configure
sed -i '70,75 d' app/core/gimpparamspecs-duplicate.c

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --without-gvfs
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache
update-desktop-database

#################
} # END OF FILE #
#################

