#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-system-monitor/3.22/gnome-system-monitor-3.22.2.tar.xz"
MD5SUMLIST="5d12860ddcf55d7116602ae22b6793fd"
REQUIRES="adwaita-icon-theme appstream-glib gtkmm3 itstool libgtop librsvg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --enable-wnck
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

