#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-desktop/3.22/gnome-desktop-3.22.2.tar.xz"
MD5SUMLIST="3d7222d5305f3db022eca31d8108e02d"
REQUIRES="gsettings-desktop-schemas gtk+3 iso-codes itstool libxml2 xkeyboard-config"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

