#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/gnome-terminal/3.22/gnome-terminal-3.22.1.tar.xz"
MD5SUMLIST="12ac4a10a93346d9f97ecff528ffd36f"
REQUIRES="appstream-glib dconf gnome-shell gsettings-desktop-schemas itstool pcre2 vte"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr             \
            --disable-static          \
            --disable-migration       \
            --disable-search-provider
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

