#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxde/gpicview-0.2.5.tar.xz"
MD5SUMLIST="26be9b0c5a234f1afe7d83d02a4a33f4"
REQUIRES="gtk+2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
sed -i 's/Utility;//' ${FAKEROOT}/usr/share/applications/gpicview.desktop

#################
} # END OF FILE #
#################

