#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.10.4.tar.xz"
MD5SUMLIST="c68d0509c9980b0b70a4b836ff73fff1"
REQUIRES="gst10-plugins-base"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --with-package-name="GStreamer Ugly Plugins 1.10.4 BLFS" \
            --with-package-origin="http://www.linuxfromscratch.org/blfs/view/svn/"
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

