#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/gimp-print/gutenprint-5.2.12.tar.bz2"
MD5SUMLIST="9789107b577d1338c1d189993ea99eef"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's|$(PACKAGE)/doc|doc/$(PACKAGE)-$(VERSION)|' \
       {,doc/,doc/developer/}Makefile.in

./configure --prefix=/usr --disable-static

make

make DESTDIR=${FAKEROOT} install
install -v -m755 -d ${FAKEROOT}/usr/share/doc/gutenprint-5.2.12/api/gutenprint{,ui2}
install -v -m644    doc/gutenprint/html/* \
                    ${FAKEROOT}/usr/share/doc/gutenprint-5.2.12/api/gutenprint
install -v -m644    doc/gutenprintui2/html/* \
                    ${FAKEROOT}/usr/share/doc/gutenprint-5.2.12/api/gutenprintui2

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

/etc/rc.d/init.d/cups restart

#################
} # END OF FILE #
#################

