#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/applications/16.12.2/src/gwenview-16.12.2.tar.xz"
MD5SUMLIST="93677b5c62e8657911489a49040ef4c2"
REQUIRES="exiv2 kf5-frameworks lcms2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$KF5_PREFIX \
      -DCMAKE_BUILD_TYPE=Release         \
      -DBUILD_TESTING=OFF                \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

