#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/project/haveged/haveged-1.9.1.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="015ff58cd10607db0e0de60aeca2f5f8
            b4f1623b69c67f10e67ca610ceee56b4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install
mkdir -pv    ${FAKEROOT}/usr/share/doc/haveged-1.9.1
cp -v README ${FAKEROOT}/usr/share/doc/haveged-1.9.1

includeBootscript haveged

#################
} # END OF FILE #
#################

