#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/hdparm/hdparm-9.51.tar.gz"
MD5SUMLIST="8fe0a71db02f7ffc602d14a69f766cff"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} binprefix=/usr install

#################
} # END OF FILE #
#################

