#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.andre-simon.de/zip/highlight-3.36.tar.bz2"
MD5SUMLIST="142e2965e1070bb223369e97da8177d9"
REQUIRES="boost lua"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make gui

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install-gui

#################
} # END OF FILE #
#################

