#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/bbidulock/icewm/releases/download/1.3.12/icewm-1.3.12.tar.bz2"
MD5SUMLIST="3e3b8904d53998c0f46414722d86457c"
REQUIRES="gdk-pixbuf xorg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################


./configure --prefix=/usr                     \
            --sysconfdir=/etc                 \
            --docdir=/usr/share/icewm-1.3.12
make

make DESTDIR=${FAKEROOT} install
rm ${FAKEROOT}/usr/share/xsessions/icewm.desktop

echo icewm-session > ${FAKEROOT}/etc/alternatives/xinitrc/icewm.xinitrc

mkdir -v ${FAKEROOT}/etc/skel/.icewm
cp -v ${FAKEROOT}/usr/share/icewm/keys ${FAKEROOT}/etc/skel/.icewm/keys
cp -v ${FAKEROOT}/usr/share/icewm/menu ${FAKEROOT}/etc/skel/.icewm/menu
cp -v ${FAKEROOT}/usr/share/icewm/preferences ${FAKEROOT}/etc/skel/.icewm/preferences
cp -v ${FAKEROOT}/usr/share/icewm/toolbar ${FAKEROOT}/etc/skel/.icewm/toolbar
cp -v ${FAKEROOT}/usr/share/icewm/winoptions ${FAKEROOT}/etc/skel/.icewm/winoptions

icewm-menu-fdo >~/.icewm/menu

cat > ${FAKEROOT}/etc/skel/.icewm/startup << "EOF"
rox -p Default &
EOF
chmod +x ${FAKEROOT}/etc/skel/.icewm/startup

#################
} # END OF FILE #
#################

