#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.imagemagick.org/download/releases/ImageMagick-7.0.4-8.tar.xz"
MD5SUMLIST="b0a7821fdc789bfa29f5f49070331be2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-hdri     \
            --with-modules    \
            --with-perl       \
            --disable-static
make

make DESTDIR=${FAKEROOT} DOCUMENTATION_PATH=/usr/share/doc/imagemagick-7.0.4 install

#################
} # END OF FILE #
#################

