#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.imagemagick.org/download/releases/ImageMagick-6.9.7-8.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/ImageMagick-6.9.7-8-libs_only-1.patch"
MD5SUMLIST="765ed15348074bc2e45acd6f890016eb
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../ImageMagick-6.9.7-8-libs_only-1.patch
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-hdri     \
            --with-modules    \
            --disable-static
make

make DESTDIR=${FAKEROOT} DOCUMENTATION_PATH=/usr/share/doc/imagemagick-6.9.7 install-libs-only

#################
} # END OF FILE #
#################

