#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.10.tar.gz"
MD5SUMLIST="06882adcf92524eb493f3cf0d3f62c9a"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir BUILD
cd    BUILD

cmake -DCMAKE_INSTALL_PREFIX=/usr    \
      -DCMAKE_BUILD_TYPE=Release     \
      -DCMAKE_SKIP_INSTALL_RPATH=YES \
      -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/jasper-2.0.10 \
      ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

