#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="___PRIMARY_SOURCE_NOT_FOUND___"
MD5SUMLIST="___PRIMARY_MD5_NOT_FOUND___"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

install -vdm755 ${FAKEROOT}/opt/OpenJDK-1.8.0.121-bin
mv -v * ${FAKEROOT}/opt/OpenJDK-1.8.0.121-bin
chown -R root:root ${FAKEROOT}/opt/OpenJDK-1.8.0.121-bin

ln -sfn OpenJDK-1.8.0.121-bin ${FAKEROOT}/opt/jdk

#################
} # END OF FILE #
#################

