#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/joe-editor/joe-4.4.tar.gz"
MD5SUMLIST="59e63debe60b456a6ee5c0c27a756a47"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/joe-4.4
make

make DESTDIR=${FAKEROOT} install

install -vm 755 joe/util/{stringify,termidx,uniproc} ${FAKEROOT}/usr/bin

install -vdm755 ${FAKEROOT}/usr/share/joe/util
install -vm 644 joe/util/{*.txt,README} ${FAKEROOT}/usr/share/joe/util

#################
} # END OF FILE #
#################

