#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="ark5 gwenview k3b kdenlive5 khelpcenter kmix5 konsole5 libkcddb libkdcraw libkexiv2 okular5"
TAGS="group"

