#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.nlnetlabs.nl/downloads/ldns/ldns-1.7.0.tar.gz"
MD5SUMLIST="74b75c9ba69fb3af2a0c26244ecfd9f6"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --disable-static        \
            --disable-dane-ta-usage \
            --with-drill
make

make doc

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/ldns-1.7.0
install -v -m644 doc/html/* ${FAKEROOT}/usr/share/doc/ldns-1.7.0

#################
} # END OF FILE #
#################

