#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.ivmaisoft.com/_bin/atomic_ops/libatomic_ops-7.4.4.tar.gz"
MD5SUMLIST="426d804baae12c372967a6d183e25af2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's#pkgdata#doc#' doc/Makefile.am
autoreconf -fi
./configure --prefix=/usr    \
            --enable-shared  \
            --disable-static \
            --docdir=/usr/share/doc/libatomic_ops-7.4.4
make

make DESTDIR=${FAKEROOT} install
mv -v   ${FAKEROOT}/usr/share/libatomic_ops/* \
        ${FAKEROOT}/usr/share/doc/libatomic_ops-7.4.4
rm -vrf ${FAKEROOT}/usr/share/libatomic_ops

#################
} # END OF FILE #
#################

