#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.videolan.org/libdvdcss/1.4.0/libdvdcss-1.4.0.tar.bz2"
MD5SUMLIST="2edba36e6af3f0223c4f0454cdf3d159"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/libdvdcss-1.4.0
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

