#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/libical/libical/releases/download/v2.0.0/libical-2.0.0.tar.gz"
MD5SUMLIST="6bf8e5f5a3ba88baf390d0134e05d76e"
REQUIRES="cmake"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DCMAKE_BUILD_TYPE=Release       \
      -DSHARED_ONLY=yes                \
      ..
make

make docs

make DESTDIR=${FAKEROOT} install

install -vdm755 ${FAKEROOT}/usr/share/doc/libical-2.0.0/html
cp -vr apidocs/html/* ${FAKEROOT}/usr/share/doc/libical-2.0.0/html

#################
} # END OF FILE #
#################

