#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnu.org/gnu/libidn/libidn-1.33.tar.gz"
MD5SUMLIST="a9aa7e003665de9c82bd3f9fc6ccf308"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

find doc -name "Makefile*" -delete
rm -rf -v doc/{gdoc,idn.1,stamp-vti,man,texi}
mkdir -v       ${FAKEROOT}/usr/share/doc/libidn-1.33
cp -r -v doc/* ${FAKEROOT}/usr/share/doc/libidn-1.33

#################
} # END OF FILE #
#################

