#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/cjlin1/liblinear/archive/v211.tar.gz"
MD5SUMLIST="9aa46bea862a82d7bdb86017e94feffc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make lib

install -vm644 linear.h ${FAKEROOT}/usr/include
install -vm755 liblinear.so.3 ${FAKEROOT}/usr/lib
ln -sfv liblinear.so.3 ${FAKEROOT}/usr/lib/liblinear.so

#################
} # END OF FILE #
#################

