#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/libmng/libmng-2.0.3.tar.xz"
MD5SUMLIST="e9e899adb1b681b17f14d91e261878c5"
REQUIRES="lcms2 libjpeg-turbo"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static
make

make DESTDIR=${FAKEROOT} install

install -v -m755 -d        ${FAKEROOT}/usr/share/doc/libmng-2.0.3
install -v -m644 doc/*.txt ${FAKEROOT}/usr/share/doc/libmng-2.0.3

#################
} # END OF FILE #
#################

