#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.tcpdump.org/release/libpcap-1.8.1.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/libpcap-1.8.1-enable_bluetooth-1.patch"
MD5SUMLIST="3d48f9cd171ff12b0efd9134b52f1447
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../libpcap-1.8.1-enable_bluetooth-1.patch

./configure --prefix=/usr
make

sed -i '/INSTALL_DATA.*libpcap.a\|RANLIB.*libpcap.a/ s/^/#/' Makefile

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

