#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.documentfoundation.org/libreoffice/src/5.3.0/libreoffice-5.3.0.3.tar.xz
          http://download.documentfoundation.org/libreoffice/src/5.3.0/libreoffice-dictionaries-5.3.0.3.tar.xz
          http://download.documentfoundation.org/libreoffice/src/5.3.0/libreoffice-help-5.3.0.3.tar.xz
          http://download.documentfoundation.org/libreoffice/src/5.3.0/libreoffice-translations-5.3.0.3.tar.xz"
MD5SUMLIST="204c492a0b5e58dd0be9788c74a364ab
            dontverify
            dontverify
            dontverify"
REQUIRES="perl-archive-zip unzip wget which zip"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf libreoffice-5.3.0.3.tar.xz --no-overwrite-dir
cd libreoffice-5.3.0.3

install -dm755 external/tarballs
ln -sv ../../../libreoffice-dictionaries-5.3.0.3.tar.xz external/tarballs/
ln -sv ../../../libreoffice-help-5.3.0.3.tar.xz         external/tarballs/

ln -sv ../../../libreoffice-translations-5.3.0.3.tar.xz external/tarballs/

export LO_PREFIX=<PREFIX>

sed -e "/gzip -f/d"   \
    -e "s|.1.gz|.1|g" \
    -i bin/distro-install-desktop-integration

sed -e "/distro-install-file-lists/d" -i Makefile.in

./autogen.sh --prefix=$LO_PREFIX         \
             --sysconfdir=/etc           \
             --with-vendor=BLFS          \
             --with-lang='fr en-GB'      \
             --with-help                 \
             --with-myspell-dicts        \
             --with-alloc=system         \
             --without-junit             \
             --without-system-dicts      \
             --disable-dconf             \
             --disable-odk               \
             --disable-firebird-sdbc     \
             --enable-release-build=yes  \
             --enable-python=system      \
             --with-system-apr           \
             --with-system-boost         \
             --with-system-cairo         \
             --with-system-clucene       \
             --with-system-curl          \
             --with-system-expat         \
             --with-system-graphite      \
             --with-system-harfbuzz      \
             --with-system-icu           \
             --with-system-jpeg          \
             --with-system-lcms2         \
             --with-system-libatomic_ops \
             --with-system-libpng        \
             --with-system-libxml        \
             --with-system-neon          \
             --with-system-nss           \
             --with-system-odbc          \
             --with-system-openldap      \
             --with-system-openssl       \
             --with-system-poppler       \
             --with-system-postgresql    \
             --with-system-redland       \
             --with-system-serf          \
             --with-system-zlib

make build-nocheck

make DESTDIR=${FAKEROOT} distro-pack-install

if [ "$LO_PREFIX" != "/usr" ]; then

  # This symlink is necessary for the desktop menu entries
  ln -svf $LO_PREFIX/lib/libreoffice/program/soffice ${FAKEROOT}/usr/bin/libreoffice

  # Icons
  mkdir -vp ${FAKEROOT}/usr/share/pixmaps
  for i in $LO_PREFIX/share/icons/hicolor/32x32/apps/*; do
    ln -svf $i ${FAKEROOT}/usr/share/pixmaps
  done

  # Desktop menu entries
  for i in $LO_PREFIX/lib/libreoffice/share/xdg/*; do
    ln -svf $i ${FAKEROOT}/usr/share/applications/libreoffice-$(basename $i)
  done

  # Man pages
  for i in $LO_PREFIX/share/man/man1/*; do
    ln -svf $i ${FAKEROOT}/usr/share/man/man1/
  done

  unset i
fi

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

update-desktop-database

#################
} # END OF FILE #
#################

