#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/logrotate/logrotate/releases/download/3.11.0/logrotate-3.11.0.tar.xz"
MD5SUMLIST="3a9280e4caeb837427a2d54518fbcdac"
REQUIRES="popt"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/exit 5/s/^/echo uncompress failed -- skipping #/' test/test

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

cat > ${FAKEROOT}/etc/logrotate.conf << EOF
# Begin of ${FAKEROOT}/etc/logrotate.conf

# Rotate log files weekly
weekly

# Don't mail logs to anybody
nomail

# If the log file is empty, it will not be rotated
notifempty

# Number of backups that will be kept
# This will keep the 2 newest backups only
rotate 2

# Create new empty files after rotating old ones
# This will create empty log files, with owner
# set to root, group set to sys, and permissions 644
create 0664 root sys

# Compress the backups with gzip
compress

# No packages own lastlog or wtmp -- rotate them here
/var/log/wtmp {
    monthly
    create 0664 root utmp
    rotate 1
}

/var/log/lastlog {
    monthly
    rotate 1
}

# Some packages drop log rotation info in this directory
# so we include any file in it.
include ${FAKEROOT}/etc/logrotate.d

# End of ${FAKEROOT}/etc/logrotate.conf
EOF

chmod -v 0644 ${FAKEROOT}/etc/logrotate.conf

cat > ${FAKEROOT}/etc/logrotate.d/sys.log << EOF
/var/log/sys.log {
   # If the log file is larger than 100kb, rotate it
   size   100k
   rotate 5
   weekly
   postrotate
      ${FAKEROOT}/bin/killall -HUP syslogd
   endscript
}
EOF

chmod -v 0644 ${FAKEROOT}/etc/logrotate.d/sys.log

cat > ${FAKEROOT}/etc/logrotate.d/example.log << EOF
file1
file2
file3 {
   ...
   postrotate
    ...
   endscript
}
EOF

chmod -v 0644 ${FAKEROOT}/etc/logrotate.d/example.log

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

 mkdir -p /etc/logrotate.d

#################
} # END OF FILE #
#################

