#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.mirrorservice.org/sites/lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_4.89.tar.bz2"
MD5SUMLIST="1b9cd34f3fb86856a125abbf2be3a386"
REQUIRES="libtirpc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

tar -xf lsof_4.89_src.tar
cd lsof_4.89_src
./Configure -n linux
make CFGL="-L./lib -ltirpc"

install -v -m0755 -o root -g root lsof ${FAKEROOT}/usr/bin
install -v lsof.8 ${FAKEROOT}/usr/share/man/man8

#################
} # END OF FILE #
#################

