#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxde/lxde-common-0.99.2.tar.xz"
MD5SUMLIST="14a9d19c4576dc15d985453ccb8ca9f6"
REQUIRES="lxde-icon-theme lxpanel lxsession openbox pcmanfm"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

update-mime-database /usr/share/mime
gtk-update-icon-cache -qf /usr/share/icons/hicolor
update-desktop-database -q

#################
} # END OF FILE #
#################

