#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxde/lxde-icon-theme-0.5.1.tar.xz"
MD5SUMLIST="7467133275edbbcc79349379235d4411"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache -qf /usr/share/icons/nuoveXT2

#################
} # END OF FILE #
#################

