#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.lxqt.org/lximage-qt/0.5.1/lximage-qt-0.5.1.tar.xz"
MD5SUMLIST="90b79b017649a06b0eb6178590143856"
REQUIRES="libexif libfm-qt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -v build
cd       build

cmake -DCMAKE_BUILD_TYPE=Release          \
      -DCMAKE_INSTALL_PREFIX=$LXQT_PREFIX \
      -DPULL_TRANSLATIONS=no              \
      ..

make

make DESTDIR=${FAKEROOT} install

ln -svf $LXQT_PREFIX/share/applications/lximage-qt.desktop \
        ${FAKEROOT}/usr/share/applications

ln -svf $LXQT_PREFIX/share/applications/lximage-qt-screenshot.desktop \
        ${FAKEROOT}/usr/share/applications

#################
} # END OF FILE #
#################

