#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="libfm-qt liblxqt libqtxdg libsysstat lxqt-about lxqt-admin lxqt-build-tools lxqt-common lxqt-config lxqt-globalkeys lxqt-kguiaddons lxqt-kidletime lxqt-kwayland lxqt-kwindowsystem lxqt-l10n lxqt-libkscreen lxqt-notificationd lxqt-panel lxqt-policykit lxqt-powermanagement lxqt-qtplugin lxqt-runner lxqt-session lxqt-solid pcmanfm-qt"
TAGS="group"

