#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/frameworks/5.31/kguiaddons-5.31.0.tar.xz"
MD5SUMLIST="ecb1a10910116e9fd3265f2f1908c6a1"
REQUIRES="extra-cmake-modules qt5 x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -v build
cd       build

cmake -DCMAKE_INSTALL_PREFIX=$LXQT_PREFIX \
      -DCMAKE_BUILD_TYPE=Release          \
      -DCMAKE_INSTALL_LIBDIR=lib          \
      -DBUILD_TESTING=OFF                 \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

