#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/lxde/lxqt-common/releases/download/0.11.2/lxqt-common-0.11.2.tar.xz"
MD5SUMLIST="3722ca91903e48c62d1ba73edf19721c"
REQUIRES="hicolor-icon-theme liblxqt x7app"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e '/TryExec/s@=@='$LXQT_PREFIX'/bin/@' \
    -i xsession/lxqt.desktop.in

mkdir -v build
cd       build

cmake -DCMAKE_BUILD_TYPE=Release          \
      -DCMAKE_INSTALL_PREFIX=$LXQT_PREFIX \
      ..

make

mkdir -pv $LXQT_PREFIX/share/lxqt/graphics
make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

