#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/lxde/lxqt-qtplugin/releases/download/0.11.1/lxqt-qtplugin-0.11.1.tar.xz"
MD5SUMLIST="e30d35f03f6a8351c79782d68b91a0e9"
REQUIRES="libdbusmenuqt liblxqt"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -v build
cd       build

cmake -DCMAKE_BUILD_TYPE=Release          \
      -DCMAKE_INSTALL_PREFIX=$LXQT_PREFIX \
      ..

make

make DESTDIR=${FAKEROOT} install

cat >> ${FAKEROOT}/etc/profile.d/lxqt.sh << "EOF"
# Begin lxqt-qtplugin configuration

export QT_QPA_PLATFORMTHEME=lxqt

# End lxqt-qtplugin configuration
EOF

#################
} # END OF FILE #
#################

