#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/lxde/lxsession-0.5.3.tar.xz"
MD5SUMLIST="823c50e6d0e4ce15a23a42e8f8bf4221"
REQUIRES="dbus-glib libunique lsb-release polkit vala"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-man
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

