#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.debian.org/debian/pool/main/h/heirloom-mailx/heirloom-mailx_12.5.orig.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/heirloom-mailx-12.5-fixes-1.patch"
MD5SUMLIST="29a6033ef1412824d02eb9d9213cb1f2
            dontverify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../heirloom-mailx-12.5-fixes-1.patch
make SENDMAIL=/usr/sbin/sendmail -j1

make DESTDIR=${FAKEROOT} PREFIX=/usr UCBINSTALL=/usr/bin/install install
ln -v -sf mailx ${FAKEROOT}/usr/bin/mail
ln -v -sf mailx ${FAKEROOT}/usr/bin/nail
install -v -m755 -d ${FAKEROOT}/usr/share/doc/heirloom-mailx-12.5
install -v -m644 README ${FAKEROOT}/usr/share/doc/heirloom-mailx-12.5

#################
} # END OF FILE #
#################

