#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-4.0.tar.xz"
MD5SUMLIST="2cb4feffea9167ba71b5f346a0c0a40d"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

sed -i 's# if.* == "1"#& -a -e $targetdir/log#' test
make test

./test --keep-going --logdir=test-logs --save-logs

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

