#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.mercurial-scm.org/release/mercurial-4.1.3.tar.gz"
MD5SUMLIST="7cfdc8c038dae92c2745644a4b8ac5ef"
REQUIRES="python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make build

make doc

# (*) Don't run test suites.
#rm -rf tests/tmp
#
#TESTFLAGS="-j<N> --tmpdir tmp --blacklist blacklists/failed-tests" \
#make check

make DESTDIR=${FAKEROOT} PREFIX=/usr install-bin

make DESTDIR=${FAKEROOT} PREFIX=/usr install-doc

cat >> ~/.hgrc << "EOF"
[ui]
username = <user_name> <user@mail>
EOF

install -v -d -m755 ${FAKEROOT}/etc/mercurial
cat >> ${FAKEROOT}/etc/mercurial/hgrc << "EOF"
[web]
cacerts = /etc/ssl/ca-bundle.crt
EOF

#################
} # END OF FILE #
#################

