#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.midori-browser.org/downloads/midori_0.5.11_all_.tar.bz2"
MD5SUMLIST="fcc03ef759fce4fe9f2446d9da4a065e"
REQUIRES="cmake gcr libnotify vala webkitgtk"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DUSE_ZEITGEIST=OFF         \
      -DHALF_BRO_INCOM_WEBKIT2=ON \
      -DUSE_GTK3=1                \
      -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/midori-0.5.11 \
      ..
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

