#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.3.0.tar.xz
          https://www.mplayerhq.hu/MPlayer/skins/Clearlooks-1.7.tar.bz2"
MD5SUMLIST="e8a4d77ad4f509e81dd5e13b51636c1d
            dontverify"
REQUIRES="yasm"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr            \
            --confdir=/etc/mplayer   \
            --enable-dynamic-plugins \
            --enable-menu            \
            --enable-gui
make

make doc

make DESTDIR=${FAKEROOT} install
ln -svf ../icons/hicolor/48x48/apps/mplayer.png \
        ${FAKEROOT}/usr/share/pixmaps/mplayer.png

install -v -m755 -d ${FAKEROOT}/usr/share/doc/mplayer-1.3.0
install -v -m644    DOCS/HTML/en/* \
                    ${FAKEROOT}/usr/share/doc/mplayer-1.3.0

install -v -m644 etc/codecs.conf ${FAKEROOT}/etc/mplayer

install -v -m644 etc/*.conf ${FAKEROOT}/etc/mplayer

tar -xvf  ../Clearlooks-1.7.tar.bz2 \
    -C    ${FAKEROOT}/usr/share/mplayer/skins
ln  -sfvn Clearlooks ${FAKEROOT}/usr/share/mplayer/skins/default

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache
update-desktop-database

#################
} # END OF FILE #
#################

