#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="alsa-firmware alsa-lib alsa-oss alsa-plugins alsa-tools alsa-utils audiofile faac faad2 fdk-aac flac flashplayer frei0r gavl gst10-libav gst10-plugins-bad gst10-plugins-base gst10-plugins-good gst10-plugins-ugly gstreamer10 gstreamer10-vaapi liba52 libao libass libcanberra libcddb libcdio libdiscid libdv libdvdcss libdvdnav libdvdread libmad libmpeg2 libmusicbrainz libmusicbrainz5 libogg libquicktime libsamplerate libsndfile libtheora libvorbis libvpx mlt opal opus pulseaudio sbc sdl sdl2 soundtouch speex taglib v4l-utils x264 x265 xine-lib xvid"
TAGS="group"

