#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/nautilus/3.22/nautilus-3.22.3.tar.xz"
MD5SUMLIST="ba8fa4513b4ec218e411ee3ef34fda53"
REQUIRES="gnome-autoar gnome-desktop libnotify"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --disable-selinux    \
            --disable-tracker    \
            --disable-packagekit
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

