#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/nfs/nfs-utils-2.1.1.tar.bz2
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="1157abcfaa8670f990f408cf280426b4
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="libtirpc rpcbind"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr          \
            --sysconfdir=/etc      \
            --without-tcp-wrappers \
            --disable-nfsv4        \
            --disable-gss
make

make DESTDIR=${FAKEROOT} install
chmod u+w,go+r ${FAKEROOT}/sbin/mount.nfs

includeBootscript nfs-server

cat > ${FAKEROOT}/etc/sysconfig/nfs-server << "EOF"
PORT="2049"
PROCESSES="8"
QUOTAS="no"
KILLDELAY="10"
EOF

includeBootscript nfs-client

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 99 nogroup
useradd -c "Unprivileged Nobody" -d /dev/null -g nogroup \
    -s /bin/false -u 99 nobody

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

/home 192.168.0.0/24(rw,subtree_check,anonuid=99,anongid=99)

<server-name>:/home  /home nfs   rw,_netdev 0 0
<server-name>:/usr   /usr  nfs   ro,_netdev 0 0

#################
} # END OF FILE #
#################

