#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/opal/3.10/opal-3.10.10.tar.xz
          http://www.linuxfromscratch.org/patches/blfs/svn/opal-3.10.10-ffmpeg2-1.patch"
MD5SUMLIST="6efa1b4c5e0ad6460019b4c6df0898d7
            dontverify"
REQUIRES="ptlib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../opal-3.10.10-ffmpeg2-1.patch

sed -e 's/CODEC_ID/AV_&/' \
    -e 's/PIX_FMT_/AV_&/' \
    -i plugins/video/H.263-1998/h263-1998.cxx \
       plugins/video/common/dyna.cxx          \
       plugins/video/H.264/h264-x264.cxx      \
       plugins/video/MPEG4-ffmpeg/mpeg4.cxx

sed -e '/<< mime.PrintContents/ s/mime/(const std::string\&)&/' \
    -i src/im/msrp.cxx

./configure --prefix=/usr
CXXFLAGS=-Wno-deprecated-declarations make

make DESTDIR=${FAKEROOT} install
chmod -v 644 ${FAKEROOT}/usr/lib/libopal_s.a

#################
} # END OF FILE #
#################

