#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/3.2.0/opencv-3.2.0.zip"
MD5SUMLIST="bfc6a261eb069b709bcfe7e363ef5899"
REQUIRES="cmake unzip"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

ipp_file=../ippicv_linux_20151201.tgz
ipp_hash=$(md5sum $ipp_file | cut -d" " -f1)
ipp_dir=3rdparty/ippicv/downloads/linux-$ipp_hash

mkdir -p $ipp_dir
cp $ipp_file $ipp_dir

tar xf ../opencv_contrib-3.2.0.tar.gz

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr      \
      -DWITH_XINE=ON                   \
      -DBUILD_TESTS=OFF                \
      -DENABLE_PRECOMPILED_HEADERS=OFF \
      -Wno-dev  ..
make

make DESTDIR=${FAKEROOT} install

case $(uname -m) in
  x86_64) ARCH=intel64 ;;
       *) ARCH=ia32    ;;
esac

cp -v 3rdparty/ippicv/ippicv_lnx/lib/$ARCH/libippicv.a ${FAKEROOT}/usr/lib
unset ARCH

#################
} # END OF FILE #
#################

