#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/frameworks/5.31/oxygen-icons5-5.31.0.tar.xz"
MD5SUMLIST="385ddb6e36639dfffb0bf30b75b049e0"
REQUIRES="extra-cmake-modules qt5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/( oxygen/ s/)/scalable )/' CMakeLists.txt

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr -Wno-dev ..

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

