#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/p7zip/p7zip_16.02_src_all.tar.bz2"
MD5SUMLIST="a0128d661cfe7cc8c121e73519c54fbf"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make all3

make DESTDIR=${FAKEROOT} DEST_HOME=/usr \
     DEST_MAN=/usr/share/man \
     DEST_SHARE_DOC=/usr/share/doc/p7zip-16.02 install

#################
} # END OF FILE #
#################

