#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/pcmanfm/pcmanfm-1.2.5.tar.xz"
MD5SUMLIST="b4d1f8ce08d87e4f27805a246fc51ac2"
REQUIRES="libfm"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

