#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/pidgin/pidgin-2.12.0.tar.bz2"
MD5SUMLIST="8287400c4e5663e0e7844e868d5152af"
REQUIRES="gtk+2"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --with-gstreamer=1.0 \
            --disable-avahi      \
            --disable-gtkspell   \
            --disable-meanwhile  \
            --disable-idn        \
            --disable-nm         \
            --disable-vv         \
            --disable-tcl
make

make DESTDIR=${FAKEROOT} install
mkdir -pv ${FAKEROOT}/usr/share/doc/pidgin-2.12.0
cp -v README doc/gtkrc-2.0 ${FAKEROOT}/usr/share/doc/pidgin-2.12.0

mkdir -pv ${FAKEROOT}/usr/share/doc/pidgin-2.12.0/api
cp -v doc/html/* ${FAKEROOT}/usr/share/doc/pidgin-2.12.0/api

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

gtk-update-icon-cache
update-desktop-database

#################
} # END OF FILE #
#################

