#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="consolekit cracklib cyrus-sasl gnupg2 gnutls gpgme haveged iptables libcap libpwquality linux-pam mitkrb nettle nss openssh openssl p11-kit polkit shadow ssh-askpass stunnel sudo tripwire"
TAGS="group"

