#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.ring.gr.jp/archives/net/mail/procmail/procmail-3.22.tar.gz"
MD5SUMLIST="1678ea99b973eb77eda4ecf6acae53f1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/getline/get_line/' src/*.[ch]

make DESTDIR=${FAKEROOT} LOCKINGTEST=/tmp MANDIR=/usr/share/man install
make DESTDIR=${FAKEROOT} install-suid

#################
} # END OF FILE #
#################

