#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://pypi.python.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz"
MD5SUMLIST="55a61a054aa66812daf5161a0d5d7eda"
REQUIRES="python2 python3"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

python setup.py build

python setup.py install --optimize=1

python3 setup.py build

python3 setup.py install --optimize=1

#################
} # END OF FILE #
#################

