#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.kde.org/stable/qca/2.1.1/src/qca-2.1.1.tar.xz"
MD5SUMLIST="657cc701316600199199a6b6cb2c73c9"
REQUIRES="cacerts cmake qt5 which"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/BSD/DEFAULT/' CMakeLists.txt

sed -i 's@ca-bundle.pem@ca-bundle.crt@' CMakeLists.txt

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=$QT5DIR            \
      -DCMAKE_INSTALL_LIBDIR=lib                \
      -DCMAKE_BUILD_TYPE=Release                \
      -DQCA_MAN_INSTALL_DIR:PATH=/usr/share/man \
      ..

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

