#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/qpdf/qpdf-6.0.0.tar.gz"
MD5SUMLIST="e014bd3ecf1c4d1a520bbc14d84ac20e"
REQUIRES="pcre"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/qpdf-6.0.0
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

