#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://download.qt.io/archive/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.tar.xz"
MD5SUMLIST="66660cd3d9e1a6fed36e88adcb72e9fe"
REQUIRES="postlfs python2 x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

-archdatadir    /usr/lib/qt5                \
-bindir         /usr/bin/qt5                \
-plugindir      /usr/lib/qt5/plugins        \
-importdir      /usr/lib/qt5/imports        \
-headerdir      /usr/include/qt5            \
-datadir        /usr/share/qt5              \
-docdir         /usr/share/doc/qt5          \
-translationdir /usr/share/qt5/translations \
-examplesdir    /usr/share/doc/qt5/examples \

./configure -prefix         $QT5PREFIX \
            -sysconfdir     /etc/xdg   \
            -confirm-license           \
            -opensource                \
            -dbus-linked               \
            -openssl-linked            \
            -system-harfbuzz           \
            -system-sqlite             \
            -nomake examples           \
            -no-rpath                  \
            -skip qtwebengine
make

make DESTDIR=${FAKEROOT} install

find $QT5PREFIX/lib/pkgconfig -name "*.pc" -exec perl -pi -e "s, -L$PWD/?\S+,,g" {} \;

find $QT5PREFIX/ -name qt_lib_bootstrap_private.pri \
   -exec sed -i -e "s:$PWD/qtbase:/$QT5PREFIX/lib/:g" {} \;

find $QT5PREFIX/ -name \*.prl \
   -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

QT5BINDIR=$QT5PREFIX/bin

install -v -dm755 ${FAKEROOT}/usr/share/pixmaps/

install -v -Dm644 qttools/src/assistant/assistant/images/assistant-128.png \
                  ${FAKEROOT}/usr/share/pixmaps/assistant-qt5.png

install -v -Dm644 qttools/src/designer/src/designer/images/designer.png \
                  ${FAKEROOT}/usr/share/pixmaps/designer-qt5.png

install -v -Dm644 qttools/src/linguist/linguist/images/icons/linguist-128-32.png \
                  ${FAKEROOT}/usr/share/pixmaps/linguist-qt5.png

install -v -Dm644 qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  ${FAKEROOT}/usr/share/pixmaps/qdbusviewer-qt5.png

install -dm755 ${FAKEROOT}/usr/share/applications

cat > ${FAKEROOT}/usr/share/applications/assistant-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Assistant
Comment=Shows Qt5 documentation and examples
Exec=$QT5BINDIR/assistant
Icon=assistant-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Documentation;
EOF

cat > ${FAKEROOT}/usr/share/applications/designer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt5 applications
Exec=$QT5BINDIR/designer
Icon=designer-qt5.png
MimeType=application/x-designer;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > ${FAKEROOT}/usr/share/applications/linguist-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 Linguist
Comment=Add translations to Qt5 applications
Exec=$QT5BINDIR/linguist
Icon=linguist-qt5.png
MimeType=text/vnd.trolltech.linguist;application/x-linguist;
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;
EOF

cat > ${FAKEROOT}/usr/share/applications/qdbusviewer-qt5.desktop << EOF
[Desktop Entry]
Name=Qt5 QDbusViewer
GenericName=D-Bus Debugger
Comment=Debug D-Bus applications
Exec=$QT5BINDIR/qdbusviewer
Icon=qdbusviewer-qt5.png
Terminal=false
Encoding=UTF-8
Type=Application
Categories=Qt;Development;Debugger;
EOF

for file in moc uic rcc qmake DESTDIR=${FAKEROOT} lconvert lrelease lupdate; do
  ln -sfrvn $QT5BINDIR/$file ${FAKEROOT}/usr/bin/$file-qt5
done

cat > ${FAKEROOT}/etc/profile.d/qt5.sh << "EOF"
# Begin /etc/profile.d/qt5.sh

QT5DIR=/usr
export QT5DIR
pathappend $QT5DIR/bin/qt5

# End /etc/profile.d/qt5.sh
EOF

# (*) Utilize the ld.so.conf directory
mkdir -pv ${FAKEROOT}/etc/ld.so.conf.d

cat >> ${FAKEROOT}/etc/ld.so.conf.d/qt5.conf << EOF
# Begin Qt addition

/opt/qt5/lib

# End Qt addition
EOF

ldconfig

cat > ${FAKEROOT}/etc/profile.d/qt5.sh << "EOF"
# Begin /etc/profile.d/qt5.sh

QT5DIR=/opt/qt5

pathappend $QT5DIR/bin           PATH
pathappend $QT5DIR/lib/pkgconfig PKG_CONFIG_PATH

export QT5DIR

# End /etc/profile.d/qt5.sh
EOF

#################
} # END OF FILE #
#################

