#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/lxde/qterminal/releases/download/0.7.1/qterminal-0.7.1.tar.xz"
MD5SUMLIST="6c27ac08df0b6c8322729e0ad981873d"
REQUIRES="liblxqt qtermwidget"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -v build
cd       build

cmake -DCMAKE_INSTALL_PREFIX=$LXQT_PREFIX \
      -DCMAKE_BUILD_TYPE=Release          \
      -DPULL_TRANSLATIONS=no              \
      ..

LIBRARY_PATH=$LXQT_PREFIX/lib make

doxygen ../Doxyfile

make -C docs/latex

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/qterminal-0.7.1/{html,pdf}
cp -vr docs/html/* ${FAKEROOT}/usr/share/doc/qterminal-0.7.1/html

install -v -m644    docs/latex/refman.pdf \
                    ${FAKEROOT}/usr/share/doc/qterminal-0.7.1/pdf

if [ "$LXQT_PREFIX" != ${FAKEROOT}/usr ]; then
  ln -s $LXQT_PREFIX/share/qterminal ${FAKEROOT}/usr/share
fi

#################
} # END OF FILE #
#################

