#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/lxde/qtermwidget/releases/download/0.7.1/qtermwidget-0.7.1.tar.xz"
MD5SUMLIST="df50457bb12a0e12b1f547ca644c5c22"
REQUIRES="cmake qt5"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -v build
cd       build

cmake -DCMAKE_BUILD_TYPE=Release          \
      -DCMAKE_INSTALL_PREFIX=$LXQT_PREFIX \
      -DCMAKE_INSTALL_LIBDIR=lib          \
      ..

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

