#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/QupZilla/qupzilla/releases/download/v2.1.2/QupZilla-2.1.2.tar.xz"
MD5SUMLIST="84e4b9dda1e0bb5ad96f3b87f9fc1328"
REQUIRES="openssl qt5"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

export QUPZILLA_PREFIX=/usr
qmake
make

make DESTDIR=${FAKEROOT} install

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

xdg-icon-resource forceupdate --theme hicolor
update-desktop-database -q

#################
} # END OF FILE #
#################

