#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/v3.6.25/reiserfsprogs-3.6.25.tar.xz"
MD5SUMLIST="027a598b055dccb8da3aea1378a19f3c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

CFLAGS="$CFLAGS -std=gnu89" \
./configure --prefix=/usr   \
            --sbindir=/sbin

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

