#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/rpcbind/rpcbind-0.2.4.tar.bz2
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="cf10cd41ed8228fc54c316191c1f07fe
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="libtirpc"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "/servname/s:rpcbind:sunrpc:" src/rpcbind.c

./configure --prefix=/usr       \
            --bindir=/sbin      \
            --with-rpcuser=root \
            --enable-warmstarts \
            --without-systemdsystemunitdir
make

make DESTDIR=${FAKEROOT} install

includeBootscript rpcbind

#################
} # END OF FILE #
#################

