#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://download.samba.org/pub/samba/stable/samba-4.6.2.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="461def8190ffc651fd8458b24ca2a622
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="python2"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

echo "^samba4.rpc.echo.*on.*ncacn_np.*with.*object.*nt4_dc" >> selftest/knownfail

./configure                            \
    --prefix=/usr                      \
    --sysconfdir=/etc                  \
    --localstatedir=/var               \
    --with-piddir=/run/samba           \
    --with-pammodulesdir=/lib/security \
    --enable-fhs                       \
    --without-ad-dc                    \
    --without-systemd                  \
    --enable-selftest
make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/lib/libnss_win{s,bind}.so*   ${FAKEROOT}/lib
ln -v -sf ../../lib/libnss_winbind.so.2 ${FAKEROOT}/usr/lib/libnss_winbind.so
ln -v -sf ../../lib/libnss_wins.so.2    ${FAKEROOT}/usr/lib/libnss_wins.so

install -v -m644    examples/smb.conf.default ${FAKEROOT}/etc/samba

mkdir -pv ${FAKEROOT}/etc/openldap/schema

install -v -m644    examples/LDAP/README              \
                    ${FAKEROOT}/etc/openldap/schema/README.LDAP

install -v -m644    examples/LDAP/samba*              \
                    ${FAKEROOT}/etc/openldap/schema

install -v -m755    examples/LDAP/{get*,ol*} \
                    ${FAKEROOT}/etc/openldap/schema

includeBootscript samba

includeBootscript winbindd

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

ln -v -sf /usr/bin/smbspool /usr/lib/cups/backend/smb

groupadd -g 99 nogroup
useradd -c "Unprivileged Nobody" -d /dev/null -g nogroup \
    -s /bin/false -u 99 nobody

#################
} # END OF FILE #
#################

