#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://github.com/sddm/sddm/releases/download/v0.14.0/sddm-0.14.0.tar.xz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="9f03bd184ecd7118b7d3a6b8da24f997
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="cmake extra-cmake-modules qt5"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e '/UPOWER_SERVICE)/ s:^://:' \
    -i src/daemon/PowerManager.cpp

sed -e '/\$@$/s/exec/& ck-launch-session/' \
    -i data/scripts/Xsession

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -DENABLE_JOURNALD=OFF       \
      -DDBUS_CONFIG_FILENAME=sddm_org.freedesktop.DisplayManager.conf \
      -Wno-dev ..
make

make DESTDIR=${FAKEROOT} install
install -v -dm755 -o sddm -g sddm ${FAKEROOT}/var/lib/sddm

includeBootscript sddm

cat > ${FAKEROOT}/etc/pam.d/sddm << "EOF"
# Begin /etc/pam.d/sddm

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     include        system-auth

account  include        system-account
password include        system-password

session  required       pam_limits.so
session  include        system-session

# End /etc/pam.d/sddm
EOF

cat > ${FAKEROOT}/etc/pam.d/sddm-autologin << "EOF"
# Begin /etc/pam.d/sddm-autologin

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     required       pam_permit.so

account  include        system-account

password required       pam_deny.so

session  required       pam_limits.so
session  include        system-session

# End /etc/pam.d/sddm-autologin
EOF

cat > ${FAKEROOT}/etc/pam.d/sddm-greeter << "EOF"
# Begin /etc/pam.d/sddm-greeter

auth     required       pam_env.so
auth     required       pam_permit.so

account  required       pam_permit.so
password required       pam_deny.so
session  required       pam_unix.so
-session optional       pam_systemd.so

# End /etc/pam.d/sddm-greeter
EOF

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 64 sddm
useradd  -c "SDDM Daemon" \
         -d /var/lib/sddm \
         -u 64 -g sddm    \
         -s /bin/false sddm

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

sddm --example-config > sddm.example.conf

cp -v sddm.example.conf /etc/sddm.conf

sed -e '/ServerPath/ s|usr|opt/xorg|' \
    -i.orig /etc/sddm.conf

sed -e 's/-nolisten tcp//'\
    -i /etc/sddm.conf

sed -e 's/\"none\"/\"on\"/' \
    -i /etc/sddm.conf

/etc/rc.d/init.d/sddm start

init 5

cp -v /etc/inittab{,-orig}
sed -i '/initdefault/ s/3/5/' /etc/inittab

sddm-greeter --test-mode --theme <theme path>

echo 'setxkbmap "<your keyboard comma separated list>"' >> \
     /usr/share/sddm/scripts/Xsetup

echo "source /etc/profile.d/dircolors.sh" >> /etc/bashrc

#################
} # END OF FILE #
#################

