#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.libsdl.org/release/SDL2-2.0.5.tar.gz"
MD5SUMLIST="d4055424d556b4a908aa76fad63abd3c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

pushd docs
  doxygen
popd

make DESTDIR=${FAKEROOT} install
rm -v ${FAKEROOT}/usr/lib/libSDL2*.a

install -v -m755 -d        ${FAKEROOT}/usr/share/doc/SDL2-2.0.5/html
cp -Rv  docs/output/html/* ${FAKEROOT}/usr/share/doc/SDL2-2.0.5/html

#################
} # END OF FILE #
#################

