#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.gnome.org/pub/gnome/sources/seahorse/3.20/seahorse-3.20.0.tar.xz"
MD5SUMLIST="06cdf9805d9d1adddd0140d13f1bd234"
REQUIRES="gcr gnupg2 gpgme itstool libsecret"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i -r 's:"(/apps):"/org/gnome\1:' data/*.xml

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

