#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://archive.apache.org/dist/serf/serf-1.3.9.tar.bz2"
MD5SUMLIST="370a6340ff20366ab088012cd13f2b57"
REQUIRES="apr-util openssl scons"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i "/Append/s:RPATH=libdir,::"   SConstruct
sed -i "/Default/s:lib_static,::"    SConstruct
sed -i "/Alias/s:install_static,::"  SConstruct
scons PREFIX=/usr

scons PREFIX=/usr install

#################
} # END OF FILE #
#################

