#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://sourceforge.net/projects/smartmontools/files/smartmontools/6.5/smartmontools-6.5.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="093aeec3f8f39fa9a37593c4012d3156
            b4f1623b69c67f10e67ca610ceee56b4"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --with-initscriptdir=no \
            --docdir=/usr/share/doc/smartmontools-6.5
make

make DESTDIR=${FAKEROOT} install

includeBootscript smartd

#################
} # END OF FILE #
#################

