#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.surina.net/soundtouch/soundtouch-1.9.2.tar.gz"
MD5SUMLIST="2d1ab4abb54640e8e308e36e309c94a6"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./bootstrap
./configure --prefix=/usr \
            --docdir=/usr/share/doc/soundtouch-1.9.2
make

make DESTDIR=${FAKEROOT} install 

#################
} # END OF FILE #
#################

