#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-7.5p1.tar.gz"
MD5SUMLIST="652fdc7d8392f112bef11cacf7e69e23"
REQUIRES="gtk+2 sudo x7lib xorg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cd contrib
make gnome-ssh-askpass2

install -v -d -m755 ${FAKEROOT}/usr/libexec/openssh/contrib
install -v -m755    gnome-ssh-askpass2 \
                    ${FAKEROOT}/usr/libexec/openssh/contrib
ln -sv -f contrib/gnome-ssh-askpass2 \
                    ${FAKEROOT}/usr/libexec/openssh/ssh-askpass

cat >> ${FAKEROOT}/etc/sudo.conf << "EOF"
# Path to askpass helper program
Path askpass /usr/libexec/openssh/ssh-askpass
EOF
chmod -v 0644 ${FAKEROOT}/etc/sudo.conf

#################
} # END OF FILE #
#################

