#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.sudo.ws/dist/sudo-1.8.19p2.tar.gz"
MD5SUMLIST="31a6090ed1d0946fa22cba19e86aafef"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr              \
            --libexecdir=/usr/lib      \
            --with-secure-path         \
            --with-all-insults         \
            --with-env-editor          \
            --docdir=/usr/share/doc/sudo-1.8.19p2 \
            --with-passprompt="[sudo] password for %p: "
make

make DESTDIR=${FAKEROOT} install
ln -sfv libsudo_util.so.0.0.0 ${FAKEROOT}/usr/lib/sudo/libsudo_util.so.0

cat > ${FAKEROOT}/etc/pam.d/sudo << "EOF"
# Begin /etc/pam.d/sudo

# include the default auth settings
auth      include     system-auth

# include the default account settings
account   include     system-account

# Set default environment variables for the service user
session   required    pam_env.so

# include system session defaults
session   include     system-session

# End /etc/pam.d/sudo
EOF
chmod 644 ${FAKEROOT}/etc/pam.d/sudo

#################
} # END OF FILE #
#################

