#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://fossies.org/linux/misc/tcsh-6.20.00.tar.gz"
MD5SUMLIST="59d40ef40a68e790d95e182069431834"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's|SVID_SOURCE|DEFAULT_SOURCE|g' config/linux
sed -i 's|BSD_SOURCE|DEFAULT_SOURCE|g'  config/linux

./configure --prefix=/usr --bindir=/bin

make
sh ./tcsh.man2html

make DESTDIR=${FAKEROOT} install install.man

ln -v -sf tcsh   ${FAKEROOT}/bin/csh
ln -v -sf tcsh.1 ${FAKEROOT}/usr/share/man/man1/csh.1

install -v -m755 -d          ${FAKEROOT}/usr/share/doc/tcsh-6.20.00/html
install -v -m644 tcsh.html/* ${FAKEROOT}/usr/share/doc/tcsh-6.20.00/html
install -v -m644 FAQ         ${FAKEROOT}/usr/share/doc/tcsh-6.20.00

cat >> ${FAKEROOT}/etc/shells << "EOF"
/bin/tcsh
/bin/csh
EOF

cat > ${FAKEROOT}/etc/skel/.cshrc << "EOF"
# Original at:
# https://www.cs.umd.edu/~srhuang/teaching/code_snippets/prompt_color.tcsh.html

# Modified by the BLFS Development Team.

# Add these lines to your ~/.cshrc (or to /etc/csh.cshrc).

# Colors!
set     red="%{\033[1;31m%}"
set   green="%{\033[0;32m%}"
set  yellow="%{\033[1;33m%}"
set    blue="%{\033[1;34m%}"
set magenta="%{\033[1;35m%}"
set    cyan="%{\033[1;36m%}"
set   white="%{\033[0;37m%}"
set     end="%{\033[0m%}" # This is needed at the end...

# Setting the actual prompt.  Two separate versions for you to try, pick
# whichever one you like better, and change the colors as you want.
# Just don't mess with the ${end} guy in either line...  Comment out or
# delete the prompt you don't use.

set prompt="${green}%n${blue}@%m ${white}%~ ${green}%%${end} "
set prompt="[${green}%n${blue}@%m ${white}%~ ]${end} "

# This was not in the original URL above
# Provides coloured ls
alias ls ls --color=always

# Clean up after ourselves...
unset red green yellow blue magenta cyan yellow white end
EOF

#################
} # END OF FILE #
#################

