#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://anduin.linuxfromscratch.org/BLFS/tigervnc/tigervnc-1.7.1.tar.gz
          http://www.linuxfromscratch.org/patches/blfs/svn/tigervnc-1.7.1-gethomedir-1.patch
          https://www.x.org/pub/individual/xserver/xorg-server-1.18.4.tar.bz2"
MD5SUMLIST="82dbb9d178b8e313b51f1651e0398dfe
            dontverify
            dontverify"
REQUIRES="cmake fltk gnutls libgcrypt libjpeg-turbo pixman x7legacy xorg-env"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../tigervnc-1.7.1-gethomedir-1.patch

mkdir -vp build
cd        build

# Build viewer
cmake -G "Unix Makefiles"         \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=Release  \
      -Wno-dev ..
make

# Build server
cp -vR ../unix/xserver unix/
tar -xf ../../xorg-server-1.18.4.tar.bz2 -C unix/xserver --strip-components=1

pushd unix/xserver
  patch -Np1 -i ../../../unix/xserver117.patch
  autoreconf -fi

  ./configure $XORG_CONFIG \
      --disable-xwayland    --disable-dri        --disable-dmx         \
      --disable-xorg        --disable-xnest      --disable-xvfb        \
      --disable-xwin        --disable-xephyr     --disable-kdrive      \
      --disable-devel-docs  --disable-config-hal --disable-config-udev \
      --disable-unit-tests  --disable-selective-werror                 \
      --disable-static      --enable-dri3                              \
      --without-dtrace      --enable-dri2        --enable-glx          \
      --with-pic
  make TIGERVNC_SRCDIR=`pwd`/../../../
popd

#Install viewer
make DESTDIR=${FAKEROOT} install

#Install server
pushd unix/xserver/hw/vnc
  make DESTDIR=${FAKEROOT} install
popd

[ -e ${FAKEROOT}/usr/bin/Xvnc ] || ln -svf $XORG_PREFIX/bin/Xvnc ${FAKEROOT}/usr/bin/Xvnc

cat > ${FAKEROOT}/usr/share/applications/vncviewer.desktop << "EOF"
[Desktop Entry]
Type=Application
Name=TigerVNC Viewer
Comment=VNC client
Exec=/usr/bin/vncviewer
Icon=tigervnc
Terminal=false
StartupNotify=false
Categories=Network;RemoteAccess;
EOF

install -vm644 ../media/icons/tigervnc_24.png ${FAKEROOT}/usr/share/pixmaps
ln -sfv tigervnc_24.png ${FAKEROOT}/usr/share/pixmaps/tigervnc.png

#################
} # END OF FILE #
#################

