#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://mama.indstate.edu/users/ice/tree/src/tree-1.7.0.tgz"
MD5SUMLIST="abe3e03e469c542d8e157cdd93f4d8a6"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make

make DESTDIR=${FAKEROOT} MANDIR=/usr/share/man/man1 install
chmod -v 644 ${FAKEROOT}/usr/share/man/man1/tree.1

#################
} # END OF FILE #
#################

