#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://www.unbound.net/downloads/unbound-1.6.0.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="78409eccf7260d260b6463f85e59c66b
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="openssl"
TAGS="preinst"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  \
            --with-pidfile=/run/unbound.pid
make

make doc

make DESTDIR=${FAKEROOT} install
mv -v ${FAKEROOT}/usr/sbin/unbound-host ${FAKEROOT}/usr/bin/

install -v -m755 -d ${FAKEROOT}/usr/share/doc/unbound-1.6.0
install -v -m644 doc/html/* ${FAKEROOT}/usr/share/doc/unbound-1.6.0

includeBootscript unbound

#################################################
}; preinst() { # PRE-INSTALLATION CONFIGURATION #
#################################################

groupadd -g 88 unbound
useradd -c "Unbound DNS resolver" -d /var/lib/unbound -u 88 \
        -g unbound -s /bin/false unbound

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

echo "nameserver 127.0.0.1" > /etc/resolv.conf

sed -i '/request /i\supersede domain-name-servers 127.0.0.1;' \
       /etc/dhcp/dhclient.conf

unbound-anchor

#################
} # END OF FILE #
#################

