#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.4.tar.gz"
MD5SUMLIST="bd25d261ca1808c947cb687e2034be81"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --sysconfdir=/etc/unixODBC
make

make DESTDIR=${FAKEROOT} install

find doc -name "Makefile*" -delete
chmod 644 doc/{lst,ProgrammerManual/Tutorial}/*

install -v -m755 -d ${FAKEROOT}/usr/share/doc/unixODBC-2.3.4
cp      -v -R doc/* ${FAKEROOT}/usr/share/doc/unixODBC-2.3.4

#################
} # END OF FILE #
#################

