#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://wayland.freedesktop.org/releases/wayland-1.13.0.tar.xz"
MD5SUMLIST="cae152ed956da6de53f9727bc1c45039"
REQUIRES="libffi libxml2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --disable-documentation
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

