#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://launchpad.net/wicd/1.7/1.7.4/+download/wicd-1.7.4.tar.gz
          http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20170225.tar.xz"
MD5SUMLIST="aaa2e9f5320849e0b5d053099a6f0007
            b4f1623b69c67f10e67ca610ceee56b4"
REQUIRES="dbus-python net-tools python2 wireless-tools"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e "/wpath.logrotate\|wpath.systemd/d" \
    -e "/detection failed/ a\                self.init=\'init\/default\/wicd\'" \
    -i.orig setup.py

rm po/*.po

python setup.py configure --no-install-kde     \
                          --no-install-acpi    \
                          --no-install-pmutils \
                          --no-install-init    \
                          --no-install-gnome-shell-extensions \
                          --docdir=/usr/share/doc/wicd-1.7.4

python setup.py install --root=${FAKEROOT}

includeBootscript wicd

#################
} # END OF FILE #
#################

