#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

REQUIRES="at-spi2-atk at-spi2-core atk atkmm cairo cairomm clutter clutter-gst clutter-gtk cogl colord-gtk fltk freeglut gdk-pixbuf glu goffice010 gtk+2 gtk+3 gtk-engines gtkmm2 gtkmm3 gtksourceview imlib2 keybinder2 libdrm libepoxy libglade libnotify libxklavier pango pangomm qscintilla qt5 qtwebkit5 startup-notification webkitgtk"
TAGS="group"

