#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://oligarchy.co.uk/xapian/1.4.4/xapian-core-1.4.4.tar.xz"
MD5SUMLIST="919ad9a80a7c6a01ab4721670bb29cab"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xapian-core-1.4.4
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

