#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://archive.xfce.org/src/apps/xfce4-terminal/0.8/xfce4-terminal-0.8.4.tar.bz2"
MD5SUMLIST="7d9ea57301d6a770e5db8e7ecd6e4cda"
REQUIRES="libxfce4ui vte"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

