#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="https://www.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-4.10.0.tar.xz"
MD5SUMLIST="ddbb04493addf014db07a7e2b96b2804"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

make DEBUG=-DNDEBUG     \
     INSTALL_USER=root  \
     INSTALL_GROUP=root \
     LOCAL_CONFIGURE_OPTIONS="--enable-readline"

make DESTDIR=${FAKEROOT} PKG_DOC_DIR=/usr/share/doc/xfsprogs-4.10.0 install
make DESTDIR=${FAKEROOT} PKG_DOC_DIR=/usr/share/doc/xfsprogs-4.10.0 install-dev

rm -rfv ${FAKEROOT}/usr/lib/libhandle.a
rm -rfv ${FAKEROOT}/lib/libhandle.{a,la,so}
ln -sfv ../../lib/libhandle.so.1 ${FAKEROOT}/usr/lib/libhandle.so
sed -i "s@libdir='/lib@libdir='/usr/lib@" ${FAKEROOT}/usr/lib/libhandle.la

#################
} # END OF FILE #
#################

