#!/bin/bash

# The instructions in this file are extracted from
# 'Beyond Linux From Scratch' (2017-04-29 / r18652) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Beyond Linux From Scratch is released under the MIT license.
# Copyright (C) 2001-2017, The BLFS Development Team

WGETLIST="http://downloads.sourceforge.net/xine/xine-lib-1.2.8.tar.xz"
MD5SUMLIST="427cc4568632eea725d5169a4a50ff22"
REQUIRES="alsa ffmpeg pulseaudio xorg"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -e 's|wand/magick_wand.h|MagickWand/MagickWand.h|' \
    -i src/video_dec/image.c

sed -e 's/\(xcb-shape >= 1.0\)/xcb \1/' \
    -i m4/video_out.m4

./configure --prefix=/usr          \
            --disable-vcd          \
            --with-external-dvdnav \
            --docdir=/usr/share/doc/xine-lib-1.2.8
make

doxygen doc/Doxyfile

make DESTDIR=${FAKEROOT} install

install -v -m755 -d ${FAKEROOT}/usr/share/doc/xine-lib-1.2.8/api
install -v -m644    doc/api/* \
                    ${FAKEROOT}/usr/share/doc/xine-lib-1.2.8/api

#################
} # END OF FILE #
#################

