#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/caja-extensions-1.18.1.tar.xz"
MD5SUMLIST="e0717f239206baddf9f283ee41a4afd7"
REQUIRES="caja"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/caja-extensions \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

