#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="https://github.com/compiz-reloaded/compiz-plugins-main/releases/download/v0.8.14/compiz-plugins-main-0.8.14.tar.xz"
MD5SUMLIST="b39a9a250931285574ef296542ceb6cc"
REQUIRES="compiz compiz-bcop"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

