#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="https://github.com/compiz-reloaded/compizconfig-python/releases/download/v0.8.14/compizconfig-python-0.8.14.tar.xz"
MD5SUMLIST="27ed8f37c0b5db6c9b32fa94c829ba72"
REQUIRES="cython libcompizconfig"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

