#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="https://github.com/compiz-reloaded/emerald/releases/download/v0.8.14/emerald-0.8.14.tar.xz"
MD5SUMLIST="f1d152b57d5844cf9b00f0f705d0b534"
REQUIRES="compiz gtk+3 libwnck"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

