#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="https://github.com/compiz-reloaded/libcompizconfig/releases/download/v0.8.14/libcompizconfig-0.8.14.tar.xz"
MD5SUMLIST="962a93def3d753c8664fd1a0c1b2ec52"
REQUIRES="compiz"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
        --sysconfdir=/etc
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

