#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://downloads.yoctoproject.org/releases/matchbox/libfakekey/0.1/libfakekey-0.1.tar.bz2"
MD5SUMLIST="83dbde4d77e8baf0176fe4291d8a2303"
REQUIRES="x7lib"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr
make AM_LDFLAGS=-lX11

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

