#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/libmatemixer-1.18.0.tar.xz"
MD5SUMLIST="ec4dcf758b7dcba6c602e6ce8bf280f9"
REQUIRES="glib2 gtk-doc mate-common"
RECOMMENDS="alsa-lib"

# (*) Install 'alsa-lib' because without it, you will not be able to control ALSA devices

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/mate-mixer \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

