#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/libmateweather-1.18.0.tar.xz"
MD5SUMLIST="2f3e6493a457438e08b6034fe9ad05dc"
REQUIRES="gtk+3 gtk-doc libsoup mate-common"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/mate-weather \
        --disable-static \
        --enable-locations-compression
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

