#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/mate-media-1.18.0.tar.xz"
MD5SUMLIST="36090cba4c1f34773567690742bd124d"
REQUIRES="libcanberra libmatemixer mate-desktop"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/mate-media \
        --disable-static \
        --enable-deprecated
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

