#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

REQUIRES="mate-core mate-extras mate-runtime-dependencies"
TAGS="group"

