#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/mate-notification-daemon-1.18.0.tar.xz"
MD5SUMLIST="d2d3e92b4d3138e78ae0389f0d9aabb0"
REQUIRES="dbus-glib libcanberra libnotify libwnck mate-common"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/mate-notification-daemon \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

