#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/mate-settings-daemon-1.18.1.tar.xz"
MD5SUMLIST="b7d4c903f941715bfff7b2c95f2c32bd"
REQUIRES="dbus-glib libmatekbd mate-desktop"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/mate-settings-daemon \
        --disable-static
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

