#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/mate-panel-1.18.1.tar.xz"
MD5SUMLIST="b01c3d72183b1a1e0ff627f17833c223"
REQUIRES="dbus-glib libcanberra libmateweather librsvg libwnck mate-desktop mate-menus"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --libexecdir=/usr/lib/mate-panel \
        --mandir=/usr/share/man \
        --disable-static \
        --enable-introspection \
        --enable-matecomponent
make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

