#!/bin/bash

# This file is part of LFScript. LFScript is released under the MIT license.
# Copyright (C) 2007-2017 Marcel van den Boer

WGETLIST="http://pub.mate-desktop.org/releases/1.18/mate-session-manager-1.18.0.tar.xz"
MD5SUMLIST="cbea9714d953fddd8fcb2307db889f26"
REQUIRES="dbus-glib gtk+3 mate-common"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./autogen.sh --prefix=/usr \
        --sysconfdir=/etc/mate/1.18 \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --libexecdir=/usr/lib/mate-session-manager \
        --disable-static \
        --enable-splash
make

make DESTDIR=${FAKEROOT} install

echo "exec mate-session" \
        > ${FAKEROOT}/etc/alternatives/xinitrc/Mate.xinitrc

#################
} # END OF FILE #
#################

